CREATE DATABASE appetitedb;

\c appetitedb;

-- Tabela: categorias
CREATE TABLE categorias (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL
);

-- Tabela: receitas
CREATE TABLE receitas (
  id SERIAL PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  descricao TEXT,
  ingredientes TEXT,
  modo_preparo TEXT,
  imagem TEXT,
  favorita BOOLEAN DEFAULT FALSE,
  avaliacao INTEGER CHECK (avaliacao >= 1 AND avaliacao <= 5),
  tempo_preparo INTEGER,
  dificuldade VARCHAR(30) CHECK (dificuldade IN ('FACIL', 'MEDIO', 'DIFICIL')) NOT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  categoria_id INTEGER REFERENCES categorias(id) ON DELETE SET NULL,
  UNIQUE (titulo)
);

CREATE TABLE receita_categorias (
  receita_id INTEGER REFERENCES receitas(id) ON DELETE CASCADE,
  categoria_id INTEGER REFERENCES categorias(id) ON DELETE CASCADE,
  PRIMARY KEY (receita_id, categoria_id)
);

INSERT INTO categorias (nome) VALUES 
('Sobremesas'),
('Massas'),
('Carnes'),
('Vegetariano'),
('Lanches'),
('Bebidas'),
('Sopas');

INSERT INTO receitas (titulo, descricao, ingredientes, modo_preparo, imagem, favorita, avaliacao, tempo_preparo, dificuldade, categoria_id) VALUES 

('Bolo de Cenoura', 'Bolo tradicional brasileiro, macio e umido, com uma deliciosa cobertura de chocolate que derrete na boca. Perfeito para o cafe da tarde.', '3 cenouras medias, 3 ovos, 1 xicara de oleo, 2 xicaras de acucar, 2 xicaras de farinha de trigo, 1 colher de sopa de fermento em po, 1 lata de leite condensado, 4 colheres de sopa de chocolate em po', 'Descasque e pique as cenouras. Bata no liquidificador as cenouras, ovos e oleo ate ficar homogeneo. Em uma tigela, misture o acucar, farinha e fermento. Adicione a mistura do liquidificador e mexa bem. Despeje em forma untada e asse a 180 graus por 40 minutos. Para a cobertura, misture leite condensado com chocolate em po e cozinhe ate engrossar. Espalhe sobre o bolo morno.', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400', TRUE, 5, 60, 'FACIL', 1),

('Pudim de Leite', 'Sobremesa classica cremosa com caramelo dourado. Uma receita tradicional que nunca sai de moda e encanta qualquer mesa.', '1 lata de leite condensado, 1 lata de leite, 3 ovos, 1 xicara de acucar para caramelo', 'Faca o caramelo derretendo o acucar em uma panela ate dourar. Despeje numa forma de pudim e gire para cobrir o fundo. No liquidificador, bata leite condensado, leite e ovos. Despeje sobre o caramelo. Asse em banho-maria a 180 graus por 1 hora. Deixe esfriar, geladeira por 4 horas e desenforme passando uma faca nas bordas.', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400', TRUE, 5, 90, 'MEDIO', 1),

('Brigadeiro', 'Doce brasileiro mais famoso, feito com leite condensado e chocolate. Irresistivel e perfeito para festas e comemoracoes.', '1 lata de leite condensado, 3 colheres de sopa de chocolate em po, 1 colher de sopa de manteiga, chocolate granulado para decorar', 'Em uma panela, misture leite condensado, chocolate em po e manteiga. Cozinhe em fogo baixo, mexendo sempre, ate desgrudar do fundo da panela (cerca de 15 minutos). Deixe esfriar, faca bolinhas com as maos untadas com manteiga e passe no chocolate granulado. Coloque em forminhas de papel.', 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400', TRUE, 5, 30, 'FACIL', 1),

('Macarrao a Carbonara', 'Prato italiano classico e elegante, com molho cremoso feito com ovos, queijo e bacon. Simplicidade e sabor em cada garfada.', '400g de espaguete, 200g de bacon, 4 gemas de ovos, 1 xicara de queijo parmesao ralado, sal e pimenta-do-reino a gosto', 'Cozinhe o macarrao em agua salgada ate ficar al dente. Frite o bacon ate ficar crocante. Em uma tigela, misture gemas com parmesao. Escorra o macarrao reservando 1 xicara da agua do cozimento. Misture o macarrao quente com bacon, retire do fogo e adicione a mistura de ovos, mexendo rapidamente. Adicione agua do cozimento se necessario. Tempere e sirva.', 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400', FALSE, 4, 25, 'FACIL', 2),

('Lasanha a Bolonhesa', 'Lasanha tradicional com molho bolonhesa rico e saboroso, intercalada com queijos cremosos. Perfeita para reunir a familia.', '500g de massa de lasanha, 500g de carne moida, 2 latas de molho de tomate, 500g de mucarela, 200g de presunto, molho branco, queijo parmesao', 'Prepare o molho refogando a carne com cebola e alho, adicione molho de tomate e temperos. Cozinhe a massa. Faca camadas alternando massa, molho bolonhesa, presunto, mucarela e molho branco. Repita as camadas, finalize com queijo parmesao e asse a 200 graus por 30 minutos ate dourar.', 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400', TRUE, 5, 90, 'MEDIO', 2),

('Nhoque de Batata', 'Massa italiana macia e saborosa, feita com batatas frescas. Acompanha perfeitamente molhos variados.', '1kg de batatas, 2 ovos, 300g de farinha de trigo, sal a gosto, molho de tomate para acompanhar', 'Cozinhe as batatas com casca ate ficarem macias. Descasque e amasse ainda quentes. Misture com ovos, sal e farinha aos poucos ate formar uma massa lisa. Faca rolinhos e corte pedacos pequenos. Passe os nhoques pelo garfo para fazer risquinhos. Cozinhe em agua fervente ate subirem a superficie. Sirva com molho de sua preferencia.', 'https://images.unsplash.com/photo-1572441713132-51c75654db73?w=400', FALSE, 4, 60, 'MEDIO', 2),

('Bife a Parmegiana', 'Classico bife empanado coberto com molho de tomate e queijo gratinado. Um prato que agrada toda a familia.', '4 bifes de alcatra, 2 ovos batidos, farinha de rosca, molho de tomate, mucarela fatiada, presunto, queijo parmesao', 'Bata os bifes para amaciá-los. Tempere com sal e pimenta. Passe na farinha, depois no ovo e na farinha de rosca. Frite ate dourar. Em um refratario, coloque os bifes, cubra com molho de tomate, presunto, mucarela e parmesao. Leve ao forno ate o queijo derreter e dourar.', 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400', TRUE, 5, 45, 'MEDIO', 3),

('Frango Assado', 'Frango inteiro temperado com ervas e especiarias, assado ate ficar dourado e suculento por fora, macio por dentro.', '1 frango inteiro, alho, limao, sal, pimenta, tomilho, alecrim, azeite, batatas para acompanhar', 'Limpe o frango e faca furos com uma faca. Prepare uma pasta com alho amassado, sal, pimenta, ervas e azeite. Esfregue bem o frango por dentro e por fora. Deixe marinar por 2 horas. Asse a 200 graus por 1 hora, regando com o proprio caldo. Sirva com batatas assadas.', 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400', TRUE, 5, 120, 'MEDIO', 3),

('Feijoada', 'Prato tipico brasileiro, feito com feijao preto e carnes variadas. Tradicao e sabor que representa nossa cultura culinaria.', '500g de feijao preto, 300g de carne seca, 200g de linguica calabresa, 200g de costelinha de porco, temperos variados', 'Deixe o feijao de molho overnight. Cozinhe as carnes separadamente. Refogue cebola, alho e temperos, adicione o feijao escorrido e as carnes. Cubra com agua e cozinhe por 2 horas em fogo baixo, mexendo ocasionalmente. Sirva com arroz, couve refogada, laranja e farofa.', 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400', FALSE, 5, 180, 'DIFICIL', 3),

('Salada Caesar', 'Salada classica americana com alface crocante, croutons dourados e molho cremoso especial. Refrescante e saborosa.', 'Alface americana, croutons, queijo parmesao, molho caesar, anchovas (opcional)', 'Lave e pique a alface em pedacos grandes. Prepare croutons tostando cubos de pao com azeite e alho. Misture a alface com o molho caesar, adicione croutons e queijo parmesao lascado. Finalize com anchovas se desejar. Sirva imediatamente para manter a crocancia.', 'https://images.unsplash.com/photo-1512852939750-1305098529bf?w=400', FALSE, 4, 15, 'FACIL', 4),

('Quiche de Legumes', 'Torta francesa salgada com base crocante e recheio cremoso de legumes. Perfeita para almocos leves e nutritivos.', 'Massa quebrada, ovos, creme de leite, queijo, abobrinha, tomate, cebola, temperos', 'Prepare a massa e forre uma forma. Refogue os legumes picados. Misture ovos, creme de leite e queijo. Combine com os legumes refogados, tempere e despeje sobre a massa. Asse a 180 graus por 35 minutos ate dourar. Deixe esfriar um pouco antes de desenformar e servir.', 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400', TRUE, 4, 50, 'MEDIO', 4),

('Hamburguer Artesanal', 'Hamburguer caseiro com carne suculenta e ingredientes frescos. Muito mais saboroso que os industrializados.', 'Carne moida, pao de hamburguer, alface, tomate, cebola, queijo, molhos especiais', 'Tempere a carne moida e faca hamburguers do tamanho desejado. Grelhe por 3-4 minutos de cada lado. Torre levemente o pao. Monte o hamburguer com alface, tomate, cebola, hamburguer, queijo e molhos. Sirva acompanhado de batatas fritas.', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400', TRUE, 5, 25, 'FACIL', 5),

('Coxinha', 'Salgado brasileiro tradicional com massa macia e recheio de frango temperado. Perfeita para festas e lanches.', 'Frango desfiado, massa de mandioca, temperos, farinha de rosca, ovos para empanar', 'Cozinhe e desfie o frango, tempere bem. Prepare a massa cozinhando agua com temperos e adicionando farinha aos poucos ate formar uma massa lisa. Modele as coxinhas com o recheio, passe no ovo e farinha de rosca. Frite em oleo quente ate dourar. Escorra em papel absorvente.', 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?w=400', TRUE, 5, 60, 'MEDIO', 5),

('Pastel de Carne', 'Pastel crocante com recheio saboroso de carne temperada. Classico da culinaria brasileira.', 'Massa de pastel, carne moida, cebola, temperos, oleo para fritar', 'Refogue a carne moida com cebola e temperos ate secar. Abra a massa, coloque o recheio, feche bem as bordas com garfo. Frite em oleo bem quente ate dourar dos dois lados. Escorra e sirva quente, acompanhado de molho de pimenta.', 'https://images.unsplash.com/photo-1627662168223-7df99068099a?w=400', FALSE, 4, 40, 'MEDIO', 5),

('Suco Detox', 'Bebida saudavel e refrescante, rica em vitaminas e minerais. Ideal para quem busca uma alimentacao equilibrada.', 'Couve, maca, limao, gengibre, agua de coco', 'Lave bem todos os ingredientes. Bata no liquidificador a couve, maca picada, suco de limao, gengibre e agua de coco ate ficar homogeneo. Coe se desejar uma textura mais lisa. Sirva gelado, preferencialmente logo apos o preparo para manter as propriedades nutricionais.', 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400', FALSE, 4, 10, 'FACIL', 6),

('Vitamina de Banana', 'Bebida cremosa e nutritiva, perfeita para o cafe da manha ou lanche da tarde. Rica em potassio e energia.', 'Bananas maduras, leite, mel, aveia (opcional)', 'Descasque as bananas e corte em rodelas. Bata no liquidificador com leite gelado e mel a gosto. Adicione aveia se desejar mais cremosidade e fibras. Bata ate ficar homogeneo e cremoso. Sirva imediatamente em copos gelados.', 'https://images.unsplash.com/photo-1553909489-cd47e0ef937f?w=400', TRUE, 5, 5, 'FACIL', 6),

('Caldo Verde', 'Sopa tradicional portuguesa, reconfortante e saborosa, perfeita para dias frios. Um classico que aquece o coracao.', 'Batatas, couve portuguesa, linguica calabresa, cebola, alho, azeite, sal', 'Refogue cebola e alho no azeite. Adicione batatas picadas e agua. Cozinhe ate as batatas ficarem macias e amasse levemente. Adicione a couve cortada bem fininha e a linguica em rodelas. Cozinhe por mais 5 minutos. Tempere e sirva quente com um fio de azeite por cima.', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400', TRUE, 5, 40, 'FACIL', 7),

('Sopa de Legumes', 'Sopa nutritiva e saudavel com variedade de legumes frescos. Reconfortante e perfeita para uma alimentacao equilibrada.', 'Cenoura, abobrinha, batata, chuchu, cebola, alho, temperos verdes', 'Refogue cebola e alho no azeite. Adicione todos os legumes picados e refogue por alguns minutos. Cubra com agua, tempere e cozinhe ate os legumes ficarem macios. Se desejar, bata parte da sopa no liquidificador para engrossar. Finalize com temperos verdes picados.', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400', FALSE, 4, 35, 'FACIL', 7),

('Paella de Frutos do Mar', 'Prato espanhol tradicional com arroz temperado com acafrao e frutos do mar frescos. Sofisticado e cheio de sabor.', 'Arroz bomba, camaroes, lulas, mexilhoes, acafrao, tomate, pimentao, alho', 'Refogue alho, tomate e pimentao. Adicione o arroz e refogue. Acrescente caldo quente com acafrao aos poucos. Disponha os frutos do mar por cima sem mexer. Cozinhe em fogo baixo por 18 minutos. Deixe descansar antes de servir.', 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=400', FALSE, 5, 45, 'DIFICIL', 3),

('Risoto de Camarao', 'Risoto cremoso italiano com camaroes suculentos. Prato elegante e sofisticado para ocasioes especiais.', 'Arroz arboreo, camaroes, caldo de peixe, vinho branco, cebola, queijo parmesao', 'Refogue cebola ate transparente. Adicione o arroz e torre levemente. Acrescente vinho branco e deixe evaporar. Adicione caldo quente uma concha de cada vez, mexendo sempre. Nos ultimos minutos, adicione camaroes e queijo parmesao. Sirva imediatamente.', 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400', TRUE, 5, 40, 'MEDIO', 2),

('Strogonoff de Carne', 'Prato russo adaptado ao paladar brasileiro, cremoso e saboroso. Acompanha perfeitamente arroz e batata palha.', 'File mignon em tiras, champignons, creme de leite, molho de tomate, mostarda, conhaque', 'Doure a carne em panela quente. Reserve. Na mesma panela, refogue champignons. Adicione molho de tomate, mostarda e creme de leite. Retorne a carne, adicione conhaque e deixe apurar. Tempere e sirva com arroz branco e batata palha.', 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400', TRUE, 5, 30, 'FACIL', 3),

('Escondidinho de Carne Seca', 'Prato tipico nordestino com pure de mandioca cremoso cobrindo carne seca saborosa. Conforto em cada colherada.', 'Carne seca, mandioca, queijo coalho, cebola, alho, leite, manteiga', 'Cozinhe e desfie a carne seca, refogue com cebola e alho. Cozinhe a mandioca, amasse com leite e manteiga ate formar um pure. Em refratario, faca camadas de carne e pure, finalize com queijo. Asse ate dourar por cima.', 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400', FALSE, 4, 60, 'MEDIO', 3),

('Moqueca de Peixe', 'Prato baiano tradicional com peixe cozido em leite de coco e dende. Sabores intensos da culinaria regional.', 'Peixe em postas, leite de coco, dende, tomate, cebola, pimentao, coentro', 'Tempere o peixe e deixe marinar. Refogue cebola, tomate e pimentao. Adicione leite de coco e dende, tempere. Coloque o peixe e cozinhe por 15 minutos sem mexer muito. Finalize com coentro. Sirva com arroz branco e pirao.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400', FALSE, 5, 35, 'MEDIO', 3),

('Bobo de Camarao', 'Prato tipico baiano cremoso feito com mandioca e camaroes. Sabor unico da culinaria afro-brasileira.', 'Camaroes, mandioca, leite de coco, dende, cebola, alho, temperos', 'Cozinhe a mandioca e bata com leite de coco ate formar um creme. Refogue camaroes com temperos. Misture o creme de mandioca com camaroes, adicione dende e tempere. Cozinhe ate encorpar. Sirva quente com arroz.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400', TRUE, 5, 45, 'MEDIO', 3),

('Mousse de Chocolate', 'Sobremesa francesa classica, leve e aerada, com sabor intenso de chocolate. Elegante e irresistivel.', 'Chocolate meio amargo, ovos, acucar, creme de leite fresco', 'Derreta o chocolate em banho-maria. Separe claras e gemas. Bata as gemas com acucar ate clarear. Misture com chocolate morno. Bata claras em neve e creme de leite separadamente. Incorpore delicadamente ao chocolate. Leve a geladeira por 4 horas.', 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=400', TRUE, 5, 20, 'MEDIO', 1),

('Torta de Limao', 'Torta refrescante com base crocante e creme de limao azedinho. Perfeita para finalizar refeicoes pesadas.', 'Biscoito triturado, manteiga, leite condensado, suco de limao, creme de leite, gelatina incolor', 'Misture biscoito triturado com manteiga derretida, forre forma e leve ao freezer. Misture leite condensado, suco de limao e gelatina dissolvida. Adicione creme de leite batido. Despeje sobre a base e geladeira por 4 horas.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400', FALSE, 4, 30, 'FACIL', 1),

('Sorvete de Morango', 'Sorvete cremoso caseiro com morangos frescos. Sobremesa refrescante e natural para os dias quentes.', 'Morangos, acucar, creme de leite, leite condensado', 'Bata morangos com acucar ate formar uma polpa. Misture com creme de leite e leite condensado. Despeje em forma e congele por 2 horas. Retire, bata novamente e congele ate endurecer. Sirva em tacas geladas.', 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400', TRUE, 5, 15, 'FACIL', 1),

('Pave de Chocolate', 'Sobremesa em camadas com biscoitos e creme de chocolate. Classica e sempre presente nas mesas brasileiras.', 'Biscoito champagne, leite, chocolate em po, leite condensado, creme de leite, manteiga', 'Prepare um creme cozinhando leite condensado, chocolate e manteiga. Deixe esfriar e misture com creme de leite batido. Molhe biscoitos no leite e monte camadas alternando biscoito e creme. Finalize com chocolate ralado. Geladeira overnight.', 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400', TRUE, 5, 30, 'FACIL', 1),

('Banoffee Pie', 'Torta inglesa com base de biscoito, doce de leite, banana e chantilly. Combinacao perfeita de sabores.', 'Biscoito triturado, manteiga, doce de leite, bananas, chantilly, chocolate para decorar', 'Misture biscoito com manteiga, forre forma e leve ao forno rapidamente. Espalhe doce de leite sobre a base fria, disponha fatias de banana. Cubra com chantilly e decore com chocolate ralado. Sirva gelada.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400', FALSE, 4, 25, 'FACIL', 1),

('Acai na Tigela', 'Sobremesa brasileira refrescante com acai batido e acompanhamentos variados. Saudavel e energetico.', 'Polpa de acai, banana, granola, mel, frutas variadas para decorar', 'Bata a polpa de acai com banana ate formar um creme roxo e espesso. Despeje em tigela e decore com granola, mel e frutas picadas como morango, banana e kiwi. Sirva imediatamente.', 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400', TRUE, 5, 10, 'FACIL', 1),

('Caipirinha', 'Drink brasileiro mais famoso mundialmente, refrescante e com sabor marcante da cachaca com limao.', 'Cachaca, limao, acucar, gelo', 'Corte o limao em pedacos pequenos. Em um copo, macere o limao com acucar usando um socador. Adicione gelo e cachaca. Misture bem e sirva imediatamente. Decore com uma fatia de limao.', 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400', FALSE, 5, 5, 'FACIL', 6),

('Smoothie Verde', 'Bebida saudavel com vegetais verdes e frutas. Rica em nutrientes e perfeita para comecar o dia com energia.', 'Espinafre, banana, maca verde, agua de coco, hortela', 'Lave bem o espinafre e hortela. Bata todos os ingredientes no liquidificador ate ficar homogeneo e cremoso. Se necessario, adicione mais agua de coco. Sirva imediatamente em copos gelados.', 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400', FALSE, 4, 8, 'FACIL', 6),

('Mojito', 'Drink cubano refrescante com hortela, limao e rum. Perfeito para dias quentes e momentos descontraidos.', 'Rum branco, hortela fresca, limao, acucar, agua com gas, gelo', 'Em um copo, macere delicadamente as folhas de hortela com acucar e suco de limao. Adicione gelo, rum e complete com agua com gas. Misture suavemente e decore com ramo de hortela.', 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400', TRUE, 4, 7, 'FACIL', 6),

('Canja de Galinha', 'Sopa brasileira reconfortante, perfeita para quando se esta doente ou precisando de carinho. Nutritiva e saborosa.', 'Galinha, arroz, cenoura, salsinha, cebola, alho', 'Cozinhe a galinha inteira ate ficar macia. Retire, desfie e reserve o caldo. No caldo, cozinhe arroz e cenoura picada. Retorne o frango desfiado, tempere e finalize com salsinha. Sirva bem quente.', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400', TRUE, 5, 50, 'FACIL', 7),

('Sopa de Abobora', 'Sopa cremosa e aveludada com sabor doce natural da abobora. Reconfortante e nutritiva.', 'Abobora cabotia, cebola, gengibre, caldo de legumes, creme de leite, temperos', 'Refogue cebola e gengibre. Adicione abobora em cubos e caldo de legumes. Cozinhe ate amolecer. Bata no liquidificador ate ficar cremoso. Volte a panela, adicione creme de leite e tempere. Sirva quente.', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400', FALSE, 4, 30, 'FACIL', 7),

('Caldinho de Feijao', 'Aperitivo brasileiro servido em copinhos, perfeito para festas e encontros. Cremoso e cheio de sabor.', 'Feijao carioca, linguica calabresa, bacon, temperos, farinha de mandioca', 'Cozinhe o feijao ate ficar bem mole. Frite bacon e linguica picados. Bata parte do feijao no liquidificador. Misture tudo, tempere e engrosse com farinha se necessario. Sirva quente em copinhos.', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400', TRUE, 5, 40, 'FACIL', 7),

('Gazpacho', 'Sopa fria espanhola com tomates frescos e vegetais. Refrescante e perfeita para dias quentes de verao.', 'Tomates maduros, pepino, pimentao, cebola, alho, azeite, vinagre, pao', 'Pique todos os vegetais. Molhe fatias de pao em agua. Bata tudo no liquidificador com azeite e vinagre ate ficar homogeneo. Tempere, coe se desejar e leve a geladeira. Sirva bem gelado.', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400', FALSE, 4, 20, 'FACIL', 7),

('Tapioca Doce', 'Lanche brasileiro feito com goma de tapioca e recheios doces. Sem gluten e muito saborosa.', 'Goma de tapioca, leite condensado, coco ralado, queijo coalho', 'Hidrate a goma de tapioca ate ficar umida. Em frigideira antiaderente, espalhe a goma formando uma panqueca. Quando comecar a grudar, adicione o recheio doce de um lado, dobre ao meio e sirva quente.', 'https://images.unsplash.com/photo-1627662168223-7df99068099a?w=400', TRUE, 4, 10, 'FACIL', 5),

('Empadao de Frango', 'Torta salgada grande com massa crocante e recheio generoso de frango. Perfeita para almocos em familia.', 'Farinha, manteiga, ovos, frango desfiado, palmito, ervilha, molho branco', 'Prepare a massa misturando farinha, manteiga e ovos. Forre uma forma grande. Misture frango desfiado com palmito, ervilha e molho branco. Recheie a torta, cubra com massa e asse ate dourar.', 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400', FALSE, 4, 80, 'MEDIO', 5),

('Esfirra de Carne', 'Salgado arabe com massa macia e recheio temperado de carne. Tradicao da culinaria sirio-libanesa.', 'Farinha, fermento, carne moida, cebola, temperos arabes, azeite', 'Prepare a massa com farinha, fermento e agua morna. Deixe crescer. Refogue carne moida com cebola e temperos arabes. Abra a massa, recheie e modele as esfirras. Asse ate dourar.', 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?w=400', TRUE, 5, 70, 'MEDIO', 5),

('Quibe Frito', 'Salgado arabe crocante por fora e macio por dentro, com recheio de carne temperada. Muito popular no Brasil.', 'Trigo para quibe, carne moida, cebola, temperos arabes, hortela', 'Hidrate o trigo para quibe. Misture com parte da carne e temperos para formar a massa. Refogue o restante da carne para o recheio. Modele os quibes, recheie e frite em oleo quente ate dourar.', 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?w=400', TRUE, 5, 60, 'MEDIO', 5),

('Wrap de Frango', 'Sanduiche enrolado em tortilha com frango grelhado e vegetais frescos. Opcao saudavel e pratica.', 'Tortilha, peito de frango, alface, tomate, cenoura, molho iogurte', 'Grelhe o frango temperado ate cozinhar completamente. Corte em tiras. Aqueça a tortilha, recheie com frango, vegetais frescos e molho. Enrole firmemente e corte ao meio para servir.', 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400', FALSE, 4, 20, 'FACIL', 5),

('Cafe Gelado', 'Bebida refrescante com cafe forte e gelo, perfeita para dias quentes. Energizante e deliciosa.', 'Cafe forte, acucar, gelo, leite (opcional)', 'Prepare um cafe forte e doce enquanto quente. Deixe esfriar completamente. Sirva em copos com bastante gelo. Adicione leite se desejar um cafe mais suave. Decore com canela em po.', 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400', FALSE, 4, 15, 'FACIL', 6),

('Cha Gelado de Frutas', 'Bebida refrescante e saudavel com cha e frutas naturais. Hidratante e cheia de sabor.', 'Cha preto, frutas vermelhas, limao, hortela, mel', 'Prepare o cha e deixe esfriar. Adicione frutas vermelhas, fatias de limao e mel a gosto. Deixe na geladeira por 2 horas para as frutas soltarem sabor. Sirva com gelo e hortela.', 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400', TRUE, 4, 10, 'FACIL', 6),

('Vitamina de Abacate', 'Bebida cremosa brasileira doce feita com abacate. Rica e nutritiva, perfeita para lanches.', 'Abacate maduro, leite, acucar, leite condensado (opcional)', 'Retire a polpa do abacate maduro. Bata no liquidificador com leite gelado e acucar ate ficar cremoso. Adicione leite condensado se desejar mais doce. Sirva imediatamente em copos gelados.', 'https://images.unsplash.com/photo-1553909489-cd47e0ef937f?w=400', TRUE, 5, 8, 'FACIL', 6),

('Biscoito de Polvilho', 'Biscoito brasileiro crocante e sem gluten, feito com polvilho. Perfeito para acompanhar cafe.', 'Polvilho doce, polvilho azedo, ovos, oleo, queijo ralado', 'Misture os polvilhos com ovos batidos, oleo quente e queijo. Amasse bem ate formar uma massa lisa. Modele biscoitinhos pequenos e asse em forno pre-aquecido ate dourar e ficar crocante.', 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400', FALSE, 4, 35, 'FACIL', 1),

('Risotto de Cogumelos', 'Risoto cremoso italiano com cogumelos variados e muito sabor. Prato sofisticado para ocasioes especiais.', 'Arroz arboreo, cogumelos variados, caldo de legumes, vinho branco, cebola, alho, queijo parmesao, azeite', 'Refogue cebola e alho. Adicione arroz e torre. Acrescente vinho branco, depois caldo aos poucos mexendo sempre. Adicione cogumelos salteados. Finalize com parmesao.', 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400', TRUE, 5, 45, 'DIFICIL', 2),

('Tiramisu', 'Sobremesa italiana classica com cafe, mascarpone e biscoitos. Elegante e irresistivel para os amantes de cafe.', 'Biscoito champagne, cafe forte, mascarpone, ovos, acucar, cacau em po, amaretto', 'Prepare cafe forte e deixe esfriar. Misture gemas com acucar, adicione mascarpone. Bata claras em neve e incorpore. Monte camadas de biscoito molhado no cafe e creme. Refrigere overnight e polvilhe cacau.', 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400', FALSE, 4, 30, 'MEDIO', 1),

('Pao de Acucar', 'Pao doce tradicional com canela e acucar. Perfeito para o cafe da manha ou lanche da tarde.', 'Farinha de trigo, fermento biologico, acucar, ovos, manteiga, leite, canela, sal', 'Dissolva fermento no leite morno. Misture farinha, acucar e sal. Adicione ovos, manteiga e leite com fermento. Sove ate ficar lisa. Deixe crescer, modele e asse ate dourar.', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400', TRUE, 4, 180, 'DIFICIL', 1),

('Salada de Quinoa', 'Salada nutritiva e colorida com quinoa, legumes frescos e molho citrico. Opcao saudavel e saborosa.', 'Quinoa, tomate cereja, pepino, cenoura, rucula, azeite, limao, sal, pimenta', 'Cozinhe quinoa ate ficar macia. Deixe esfriar. Pique todos os legumes. Misture quinoa com vegetais. Tempere com azeite, limao, sal e pimenta. Sirva gelada.', 'https://images.unsplash.com/photo-1512852939750-1305098529bf?w=400', FALSE, 3, 20, 'FACIL', 4),

('Fish and Chips', 'Prato ingles tradicional com peixe empanado crocante e batatas fritas. Classico da culinaria britanica.', 'File de peixe branco, farinha, cerveja, batatas, oleo para fritar, sal, vinagre de malte', 'Prepare massa com farinha e cerveja. Corte batatas em fatias grossas e frite. Passe peixe na massa e frite ate dourar. Sirva quente com batatas e vinagre de malte.', 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400', TRUE, 4, 40, 'MEDIO', 3),

('Panqueca Americana', 'Panquecas fofas e doces servidas com mel e frutas. Cafe da manha especial e reconfortante.', 'Farinha de trigo, acucar, fermento em po, ovos, leite, manteiga derretida, mel, frutas vermelhas', 'Misture ingredientes secos. A parte, bata ovos com leite e manteiga. Combine tudo delicadamente. Faca panquecas na frigideira. Sirva empilhadas com mel e frutas.', 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=400', FALSE, 5, 25, 'FACIL', 1),

('Guacamole', 'Pasta mexicana cremosa de abacate com temperos. Perfeita para acompanhar nachos ou como entrada.', 'Abacates maduros, limao, cebola roxa, tomate, coentro, jalapeno, sal, azeite', 'Amasse abacates com garfo deixando pedacos pequenos. Adicione cebola, tomate e jalapeno picados. Tempere com limao, sal e coentro. Sirva com tortilhas.', 'https://images.unsplash.com/photo-1449234886868-36d377ac2e2e?w=400', TRUE, 4, 15, 'FACIL', 4),

('Espaguete a Bolonhesa', 'Massa italiana classica com molho de carne rico e saboroso. Tradicional e sempre delicioso.', 'Espaguete, carne moida, tomate pelado, cebola, alho, cenoura, aipo, vinho tinto, azeite', 'Refogue cebola, alho, cenoura e aipo. Adicione carne e doure. Acrescente vinho e tomates. Cozinhe por 2 horas em fogo baixo. Sirva sobre espaguete al dente.', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400', TRUE, 5, 150, 'MEDIO', 2),

('Cheesecake de Frutas Vermelhas', 'Torta americana cremosa com base de biscoito e cobertura de frutas. Sobremesa elegante e saborosa.', 'Cream cheese, biscoito triturado, manteiga, acucar, ovos, frutas vermelhas, gelatina', 'Misture biscoito com manteiga para a base. Bata cream cheese com acucar e ovos. Despeje sobre base e asse em banho-maria. Decore com frutas vermelhas e gelatina.', 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=400', FALSE, 4, 120, 'DIFICIL', 1),

('Tacos Mexicanos', 'Tortilhas mexicanas recheadas com carne temperada e acompanhamentos frescos. Sabor autentico do Mexico.', 'Tortilhas de milho, carne moida, cebola, pimentao, tomate, alface, queijo, molho picante', 'Tempere e refogue a carne com vegetais e especiarias mexicanas. Aqueça tortilhas. Monte tacos com carne, vegetais frescos, queijo e molho. Sirva imediatamente.', 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400', TRUE, 4, 30, 'FACIL', 5),

('Salmao Grelhado', 'Peixe salmao grelhado com ervas frescas e limao. Prato saudavel e sofisticado rico em omega 3.', 'File de salmao, limao, ervas frescas, azeite, sal, pimenta, aspargos', 'Marine salmao com limao, ervas e azeite por 30 minutos. Grelhe por 4 minutos cada lado. Sirva com aspargos grelhados e fatias de limao.', 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400', FALSE, 5, 35, 'MEDIO', 3),

('Brownie de Chocolate', 'Brownie americano denso e chocolatudo. Sobremesa irresistivel para os amantes de chocolate.', 'Chocolate amargo, manteiga, acucar, ovos, farinha de trigo, nozes, essencia de baunilha', 'Derreta chocolate com manteiga. Bata ovos com acucar. Misture chocolate derretido, farinha e nozes. Asse em forma untada ate formar casquinha por cima.', 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=400', TRUE, 5, 45, 'FACIL', 1),

('Gazpacho Andaluz', 'Sopa fria espanhola tradicional com tomates e vegetais frescos. Refrescante e perfeita para verao.', 'Tomates maduros, pepino, pimentao verde, cebola, alho, azeite extra virgem, vinagre de xerez, pao', 'Retire sementes dos tomates. Bata todos ingredientes no liquidificador ate homogeneo. Coe, tempere e refrigere por 4 horas. Sirva bem gelado com azeite.', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400', FALSE, 3, 25, 'FACIL', 7),

('Frango Tikka Masala', 'Prato indiano cremoso com frango em molho de tomate e especiarias. Exotico e cheio de sabores.', 'Peito de frango, iogurte, curry, garam masala, tomate, creme de leite, cebola, gengibre, alho', 'Marine frango no iogurte com especiarias. Grelhe ate dourar. Refogue cebola, adicione tomates e especiarias. Junte frango e creme de leite. Sirva com arroz basmati.', 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400', TRUE, 4, 60, 'DIFICIL', 3),

('Smoothie Bowl de Acai', 'Tigela de acai cremoso com toppings saudaveis. Cafe da manha nutritivo e colorido.', 'Polpa de acai, banana, granola, frutas variadas, mel, coco ralado, castanhas', 'Bata acai com banana ate formar creme espesso. Despeje na tigela e decore com granola, frutas fatiadas, mel, coco e castanhas em fileiras coloridas.', 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=400', FALSE, 5, 10, 'FACIL', 6),

('Pad Thai', 'Prato tailandes tradicional com macarrao de arroz e molho agridoce. Sabores unicos da Asia.', 'Macarrao de arroz, camarao, broto de feijao, amendoim, ovos, molho de peixe, acucar de palma, limao', 'Hidrate macarrao em agua morna. Salteie camarao e ovos. Adicione macarrao, molho, acucar e amendoim. Finalize com brotos e limao. Sirva quente.', 'https://images.unsplash.com/photo-1559847844-d96692143179?w=400', TRUE, 4, 35, 'MEDIO', 2),

('Petit Four', 'Pequenos doces franceses elegantes cobertos com glace. Perfeitos para festas sofisticadas.', 'Massa de bolo, geleia, fondant, corantes alimentares, decoracoes comestiveis', 'Corte bolo em pequenos quadrados. Cubra com fina camada de geleia. Banhe com fondant colorido. Decore delicadamente. Deixe secar antes de servir.', 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=400', FALSE, 3, 90, 'DIFICIL', 1),

('Salada Grega', 'Salada mediterranea fresca com queijo feta e azeitonas. Saudavel e cheia de sabor mediterraneo.', 'Tomate, pepino, cebola roxa, azeitonas kalamata, queijo feta, azeite, oregano, limao', 'Corte tomates e pepinos em pedacos grandes. Adicione cebola em fatias, azeitonas e feta em cubos. Tempere com azeite, limao e oregano.', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400', TRUE, 4, 12, 'FACIL', 4),

('Ratatouille', 'Guisado frances de vegetais coloridos. Prato vegetariano tradicional da Provenca francesa.', 'Berinjela, abobrinha, pimentao, tomate, cebola, alho, ervas de provence, azeite', 'Corte todos vegetais em cubos uniformes. Refogue cada um separadamente. Combine numa panela com ervas e deixe cozinhar lentamente ate ficarem macios.', 'https://images.unsplash.com/photo-1572441713132-51c75654db73?w=400', FALSE, 4, 55, 'MEDIO', 4),

('Milkshake de Morango', 'Bebida cremosa e doce com morangos frescos e sorvete. Refrescante e nostalgica.', 'Morangos frescos, sorvete de baunilha, leite, acucar, chantilly para decorar', 'Bata morangos com sorvete, leite e acucar ate ficar cremoso. Sirva em copos altos decorados com chantilly e morango inteiro.', 'https://images.unsplash.com/photo-1544681280-6d311d2dd0e9?w=400', TRUE, 5, 8, 'FACIL', 6),

('Crepe Suzette', 'Crepe frances flamejado com molho de laranja e licor. Sobremesa classica e espetacular.', 'Farinha, ovos, leite, manteiga, laranja, acucar, conhaque, Grand Marnier', 'Prepare massa de crepe fina. Faca crepes e reserve. Prepare molho com suco de laranja, acucar e licor. Flameje e sirva sobre os crepes dobrados.', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400', FALSE, 3, 45, 'DIFICIL', 1),

('Wrap Vegetariano', 'Sanduiche enrolado com vegetais frescos e molho especial. Opcao saudavel e saborosa.', 'Tortilha integral, hummus, alface, cenoura, pepino, tomate, broto de alfafa, abacate', 'Espalhe hummus na tortilha. Adicione vegetais frescos em fatias. Tempere levemente e enrole firmemente. Corte ao meio para servir.', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400', TRUE, 4, 15, 'FACIL', 5),

('Osso Buco', 'Prato italiano tradicional com pernil de vitela cozido lentamente. Carne que desfia sozinha.', 'Osso buco de vitela, tomate, cebola, cenoura, aipo, vinho branco, caldo de carne', 'Doure o osso buco. Refogue vegetais. Retorne carne, adicione vinho e caldo. Cozinhe tampado por 2 horas ate a carne amolecer completamente.', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400', FALSE, 4, 180, 'DIFICIL', 3),

('Panna Cotta', 'Sobremesa italiana sedosa com gelatina e calda de frutas. Elegante e delicada.', 'Creme de leite, acucar, gelatina incolor, essencia de baunilha, frutas vermelhas para calda', 'Aqueça creme com acucar. Adicione gelatina dissolvida e baunilha. Despeje em formas e refrigere por 4 horas. Sirva desenformada com calda de frutas.', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400', TRUE, 4, 20, 'MEDIO', 1),

('Bloody Mary', 'Drink americano salgado com vodka e suco de tomate. Perfeito para brunches e ocasioes especiais.', 'Vodka, suco de tomate, molho ingles, tabasco, sal de aipo, limao, aipo para decorar', 'Misture vodka com suco de tomate gelado. Adicione molhos e temperos a gosto. Sirva em copo com gelo e decore com aipo e limao.', 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400', FALSE, 3, 5, 'FACIL', 6),

('Minestrone', 'Sopa italiana consistente com vegetais e feijao. Nutritiva e reconfortante para dias frios.', 'Feijao cannellini, tomate, cebola, cenoura, aipo, espinafre, macarrao pequeno, caldo de legumes', 'Refogue vegetais picados. Adicione tomates, feijao e caldo. Cozinhe por 30 minutos. Adicione macarrao e espinafre nos ultimos minutos. Sirva quente.', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400', TRUE, 4, 50, 'MEDIO', 7),

('Quindim', 'Doce brasileiro tradicional feito com gemas e coco. Sobremesa amarelinha e brilhante.', 'Gemas de ovos, acucar, coco ralado, manteiga para untar acucar cristal para polvilhar', 'Misture gemas peneiradas com acucar e coco. Despeje em forminhas caramelizadas. Asse em banho-maria ate firmar e dourar por cima.', 'https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?w=400', TRUE, 5, 60, 'MEDIO', 1),

('Club Sandwich', 'Sanduiche americano em camadas com frango, bacon e vegetais. Classico dos clubes americanos.', 'Pao de forma, peito de frango, bacon, alface, tomate, maionese, palitos para sustentar', 'Torre pao, grelhe frango e frite bacon. Monte sanduiche em 3 camadas com todos ingredientes. Corte em triangulos e prenda com palitos.', 'https://images.unsplash.com/photo-1553979459-d2229ba7433a?w=400', FALSE, 4, 25, 'FACIL', 5),

('Souffle de Queijo', 'Sobremesa francesa aerada que cresce no forno. Tecnica delicada mas resultado espetacular.', 'Queijo gruyere ralado, manteiga, farinha, leite, gemas, claras em neve, noz-moscada', 'Prepare molho branco grosso com queijo. Misture gemas. Incorpore claras em neve delicadamente. Asse em ramequins ate crescer e dourar.', 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=400', FALSE, 3, 35, 'DIFICIL', 1),

('Sangria Espanhola', 'Bebida espanhola refrescante com vinho e frutas. Perfeita para festas e encontros sociais.', 'Vinho tinto, frutas citricas, maca, acucar, brandy, refrigerante de limao, gelo', 'Corte frutas em pedacos. Misture com vinho, acucar e brandy. Deixe macerar por 2 horas. Na hora de servir, complete com refrigerante e gelo.', 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400', TRUE, 4, 15, 'FACIL', 6),

('Sushi California Roll', 'Sushi japones com salmao, abacate e pepino. Fresco e sofisticado da culinaria oriental.', 'Arroz japones, alga nori, salmao, abacate, pepino, maionese japonesa, gergelim', 'Cozinhe arroz japones e tempere com vinagre de arroz. Estenda alga nori sobre esteira, espalhe arroz. Coloque salmao, abacate e pepino, enrole firmemente. Corte com faca molhada e sirva com shoyu.', 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400', TRUE, 5, 60, 'DIFICIL', 3),

('Ravioli de Ricota', 'Massa fresca italiana recheada com ricota cremosa. Delicado e tradicional.', 'Massa fresca, ricota, espinafre, parmesao, ovos, noz-moscada, molho de tomate', 'Prepare massa fresca e abra fininha. Misture ricota com espinafre, parmesao e temperos. Corte circulos da massa, recheie e feche bem. Cozinhe em agua fervente ate subirem. Sirva com molho de tomate.', 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400', FALSE, 4, 120, 'DIFICIL', 2),

('Acorda Alentejana', 'Sopa portuguesa tradicional com pao, alho e coentros. Rustica e saborosa.', 'Pao alentejano, alho, coentros, azeite, ovos, sal, agua quente', 'Doure fatias de pao no azeite. Numa tigela, esmague alho com sal e coentros. Adicione azeite e agua quente. Junte pao e ovos escalfados por cima. Sirva quente.', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400', TRUE, 4, 25, 'MEDIO', 7),

('Tempura de Legumes', 'Fritura japonesa leve e crocante com vegetais frescos. Tecnica oriental refinada.', 'Abobrinha, berinjela, pimentao, farinha de trigo, agua gelada, ovo, oleo para fritar', 'Corte legumes em fatias. Prepare massa misturando farinha, ovo e agua gelada rapidamente. Passe legumes na massa e frite em oleo quente ate dourar. Sirva imediatamente com molho tentsuyu.', 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400', FALSE, 4, 30, 'MEDIO', 4),

('Creme Brulee', 'Sobremesa francesa classica com creme e acucar queimado. Elegante e refinada.', 'Creme de leite, gemas, acucar, essencia de baunilha, acucar cristal para queimar', 'Aqueça creme com baunilha. Bata gemas com acucar, misture com creme morno. Despeje em ramequins e asse em banho-maria. Refrigere por 4 horas. Antes de servir, polvilhe acucar e queime com maçarico.', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400', TRUE, 5, 90, 'DIFICIL', 1),

('Baklava', 'Doce grego folhado com nozes e mel. Crocante e muito doce.', 'Massa filo, nozes picadas, manteiga derretida, mel, acucar, canela, cravo', 'Pincele camadas de massa filo com manteiga. Intercale com nozes temperadas. Corte em losangos antes de assar. Asse ate dourar e regue com calda de mel quente.', 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400', TRUE, 4, 90, 'MEDIO', 1),

('Bibimbap', 'Prato coreano com arroz e vegetais coloridos. Nutritivo e visualmente bonito.', 'Arroz, espinafre, cenoura, broto de feijão, cogumelos, ovo, molho gochujang', 'Cozinhe arroz. Refogue cada vegetal separadamente temperado. Monte tigela com arroz no centro, vegetais em setores coloridos e ovo frito por cima. Sirva com molho picante.', 'https://images.unsplash.com/photo-1512852939750-1305098529bf?w=400', TRUE, 4, 40, 'MEDIO', 4),

('Cannoli Siciliano', 'Doce italiano com massa crocante e recheio cremoso. Tradicional da Sicilia.', 'Farinha, vinho, acucar, ricota, pistaches, chocolate, oleo para fritar', 'Prepare massa com farinha, vinho e acucar. Abra fininha e corte circulos. Enrole em formas cilindricas e frite. Para recheio, misture ricota com acucar, chocolate e pistaches. Recheie na hora de servir.', 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400', FALSE, 4, 60, 'MEDIO', 1),

('Pastrami Sandwich', 'Sanduiche americano com carne defumada e picles. Classico de delicatessen.', 'Pao centeio, pastrami fatiado, mostarda dijon, picles, queijo suico', 'Torre pao centeio levemente. Espalhe mostarda, coloque fatias generosas de pastrami, queijo e picles. Sirva com batata chips.', 'https://images.unsplash.com/photo-1553979459-d2229ba7433a?w=400', TRUE, 4, 10, 'FACIL', 5),

('Tom Yum', 'Sopa tailandesa picante e azeda com camarao. Explosao de sabores asiaticos.', 'Camaroes, cogumelos, capim limao, galanga, folhas de limao, pimenta, molho de peixe', 'Ferva agua com capim limao, galanga e folhas de limao. Adicione cogumelos e camaroes. Tempere com molho de peixe, pimenta e limao. Sirva bem quente.', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400', FALSE, 4, 20, 'FACIL', 7),

('Coq au Vin', 'Frango frances cozido no vinho tinto. Classico da culinaria francesa.', 'Frango em pedacos, vinho tinto, bacon, cogumelos, cebola, alho, ervas', 'Doure bacon e frango. Reserve. Refogue cebola e cogumelos. Retorne frango, adicione vinho e ervas. Cozinhe tampado por 1 hora ate amolecer. Sirva com pure.', 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400', TRUE, 5, 90, 'MEDIO', 3),

('Profiteroles', 'Docinhos franceses com massa choux e recheio cremoso. Elegantes e sofisticados.', 'Agua, manteiga, farinha, ovos, creme de leite, chocolate para cobertura', 'Ferva agua com manteiga. Adicione farinha de uma vez e mexa. Incorpore ovos um a um. Forme bolinhas pequenas e asse. Recheie com creme e cubra com chocolate derretido.', 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=400', FALSE, 4, 120, 'DIFICIL', 1),

('Pulled Pork', 'Carne suina desfiada americana cozida lentamente. Suculenta e saborosa.', 'Paleta suina, temperos secos, molho barbecue, pao brioche', 'Tempere carne com especiarias e cozinhe em forno baixo por 8 horas ate desfiar facilmente. Desfie e misture com molho barbecue. Sirva em pao brioche.', 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400', TRUE, 5, 480, 'DIFICIL', 3),

('Tarte Tatin', 'Torta francesa de maca invertida com caramelo. Rustica e deliciosa.', 'Macas, acucar, manteiga, massa folhada, canela', 'Caramelize acucar numa forma. Disponha fatias de maca sobre caramelo. Cubra com massa folhada e asse. Desenforme invertida para servir com caramelo por cima.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400', FALSE, 4, 60, 'MEDIO', 1),

('Shakshuka', 'Prato israelense com ovos poche em molho de tomate. Aromatico e consistente.', 'Tomates, pimentao, cebola, alho, ovos, paprica, cominho, queijo feta', 'Refogue cebola, pimentao e alho. Adicione tomates e especiarias. Cozinhe ate engrossar. Faca buracos no molho e quebre ovos. Cozinhe ate clara firmar. Sirva com pao.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400', TRUE, 4, 25, 'FACIL', 3),

('Kimchi', 'Repolho fermentado coreano picante. Probiotico e cheio de sabor.', 'Repolho chines, pimenta gochugaru, alho, gengibre, sal, acucar, peixe fermentado', 'Salmoure repolho cortado por 2 horas. Lave e escorra. Misture com pasta de pimenta, alho e gengibre. Fermente em recipiente fechado por 3-7 dias.', 'https://images.unsplash.com/photo-1512852939750-1305098529bf?w=400', FALSE, 3, 10080, 'DIFICIL', 4),

('Bangers and Mash', 'Prato ingles com salsichas e pure de batata. Reconfortante e tradicional.', 'Salsichas inglesas, batatas, manteiga, leite, cebola, molho gravy', 'Cozinhe salsichas ate dourar. Prepare pure cremoso com batatas, manteiga e leite. Faca molho com cebola refogada e caldo. Sirva salsichas sobre pure com molho.', 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400', TRUE, 4, 35, 'FACIL', 3),

('Eclair de Chocolate', 'Doce frances alongado com creme e cobertura de chocolate. Classico da confeitaria.', 'Massa choux, creme de confeiteiro, chocolate meio amargo, acucar', 'Prepare massa choux e forme bastoes. Asse ate dourar. Recheie com creme de confeiteiro. Cubra com ganache de chocolate brilhante.', 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=400', FALSE, 4, 90, 'MEDIO', 1),

('Ratatouille Tian', 'Versao elegante do ratatouille em camadas. Apresentacao sofisticada.', 'Berinjela, abobrinha, tomate, pimentao, cebola, alho, ervas de provence', 'Corte todos vegetais em fatias finas. Refogue base de cebola e alho. Disponha vegetais em camadas sobrepostas. Regue com azeite e ervas. Asse ate amolecer.', 'https://images.unsplash.com/photo-1572441713132-51c75654db73?w=400', TRUE, 5, 75, 'MEDIO', 4),

('Dim Sum Variado', 'Salgadinhos chineses no vapor. Tradicionais e delicados.', 'Massa de dumpling, camarao, porco moido, cebolinha, gengibre, molho shoyu', 'Prepare recheio misturando carnes com temperos. Abra massa fininha, recheie e modele. Cozinhe no vapor por 15 minutos. Sirva com molho de soja.', 'https://images.unsplash.com/photo-1563379091308-259c4c5a0d7b?w=400', FALSE, 4, 45, 'DIFICIL', 5),

('Mojito Virgin', 'Versao sem alcool do famoso drink cubano. Refrescante para toda familia.', 'Hortela fresca, limao, acucar, agua com gas, gelo', 'Macere hortela com acucar e suco de limao. Adicione gelo e complete com agua com gas. Misture delicadamente e sirva decorado com hortela.', 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400', TRUE, 4, 5, 'FACIL', 6),

('Shepherds Pie', 'Torta inglesa com carne e pure de batata. Reconfortante e nutritiva.', 'Carne moida de cordeiro, cebola, cenoura, ervilha, molho worcestershire, pure de batata', 'Refogue carne com vegetais e temperos. Coloque em refratario, cubra com pure de batata e asse ate dourar por cima. Sirva quente.', 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400', FALSE, 4, 50, 'MEDIO', 3),

('Madeleines', 'Bolinhos franceses em formato de concha. Delicados e perfumados.', 'Farinha, acucar, ovos, manteiga, limao, baunilha, mel', 'Bata ovos com acucar ate clarear. Adicione farinha, manteiga derretida e aromas. Despeje em formas de madeleine e asse ate dourar nas bordas.', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400', TRUE, 4, 25, 'FACIL', 1),

('Laksa', 'Sopa malaia picante com leite de coco e macarrao. Complexa e aromatica.', 'Macarrao de arroz, leite de coco, pasta de curry, camarao, ovo cozido, brotos', 'Refogue pasta de curry. Adicione leite de coco e caldo. Ferva com camaroes. Sirva sobre macarrao com ovo e brotos. Tempere com limao.', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400', FALSE, 4, 35, 'MEDIO', 7),

('Welsh Rarebit', 'Torrada galesa com queijo cremoso. Simples mas sofisticada.', 'Pao, queijo cheddar, mostarda, cerveja, manteiga, pimenta', 'Derreta queijo com cerveja e temperos ate formar creme. Torre pao e espalhe mistura por cima. Grelhe ate dourar e borbulhar.', 'https://images.unsplash.com/photo-1553979459-d2229ba7433a?w=400', TRUE, 4, 15, 'FACIL', 5),

('Kouign-Amann', 'Doce bretao folhado com caramelo. Crocante por fora, macio por dentro.', 'Farinha, fermento, manteiga salgada, acucar cristal', 'Prepare massa de pao. Incorpore manteiga em camadas como croissant. Adicione acucar entre dobras. Modele e asse ate caramelizar e dourar.', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400', FALSE, 5, 240, 'DIFICIL', 1),

('Pozole Verde', 'Sopa mexicana tradicional com milho e carne. Festiva e nutritiva.', 'Milho pozole, porco, tomatillos, jalapenos, coentro, alface, rabanete', 'Cozinhe porco ate amolecer. Bata tomatillos com jalapenos. Misture com carne e milho. Cozinhe ate espessar. Sirva com acompanhamentos frescos.', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400', TRUE, 4, 120, 'MEDIO', 7),

('Souvlaki', 'Espetinho grego de carne marinada. Aromatico e suculento.', 'Carne de porco, azeite, limao, oregano, alho, pao pita, tzatziki', 'Marine carne cortada em cubos com azeite, limao e temperos por 4 horas. Espete e grelhe ate dourar. Sirva com pita e tzatziki.', 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400', FALSE, 4, 30, 'FACIL', 3),

('Trifle Ingles', 'Sobremesa em camadas com frutas e creme. Vistosa e deliciosa.', 'Pao de lo, frutas vermelhas, creme ingles, chantilly, geleia, sherry', 'Monte camadas de pao de lo embebido em sherry, frutas, geleia, creme ingles e chantilly. Repita camadas e finalize com frutas. Geladeira por 4 horas.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400', TRUE, 4, 30, 'MEDIO', 1),

('Pancit Canton', 'Macarrao filipino salteado com vegetais. Colorido e saboroso.', 'Macarrao canton, frango, camarao, repolho, cenoura, molho de soja, calamansi', 'Hidrate macarrao. Salteie carnes, adicione vegetais e macarrao. Tempere com molhos e misture bem ate aquecer. Sirva com calamansi.', 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400', FALSE, 4, 25, 'FACIL', 2),

('Couscous Marroquino', 'Semola marroquina com vegetais e especiarias. Aromatico e nutritivo.', 'Couscous, vegetais variados, grao de bico, especiarias, caldo de legumes', 'Hidrate couscous com caldo quente. Cozinhe vegetais com especiarias em tagine. Sirva couscous com legumes por cima e caldo a parte.', 'https://images.unsplash.com/photo-1512852939750-1305098529bf?w=400', TRUE, 4, 45, 'MEDIO', 4),

('Pretzels Alemaes', 'Paes alemaes tradicionalmente salgados e macios. Classicos da Baviera.', 'Farinha, fermento, sal, bicarbonato, sal grosso para polvilhar', 'Prepare massa de pao. Modele pretzels. Ferva agua com bicarbonato e mergulhe pretzels rapidamente. Asse polvilhados com sal grosso ate dourar.', 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400', FALSE, 4, 180, 'MEDIO', 5),

('Arepas Venezuelanas', 'Paes de milho venezuelanos recheados. Versateis e nutritivos.', 'Farinha de milho pre-cozida, agua, sal, recheios variados', 'Misture farinha com agua salgada ate formar massa homogenea. Modele discos e asse em chapa ate formar casquinha. Abra e recheie a gosto.', 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400', TRUE, 4, 20, 'FACIL', 5),

('Bubble Tea', 'Cha taiwanes com bolinhas de tapioca. Divertido e refrescante.', 'Cha preto, leite, acucar, bolinhas de tapioca, gelo', 'Cozinhe bolinhas de tapioca ate ficarem translucidas. Prepare cha doce e deixe esfriar. Misture com leite, adicione bolinhas no fundo do copo e sirva com canudo grosso.', 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400', FALSE, 4, 30, 'FACIL', 6),

('Ropa Vieja', 'Prato cubano com carne desfiada em molho. Saboroso e tradicional.', 'Coxao mole, tomate, pimentao, cebola, alho, cominho, louro', 'Cozinhe carne ate amolecer e desfie. Refogue vegetais com temperos. Misture com carne desfiada e cozinhe ate o molho encorpar. Sirva com arroz.', 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400', TRUE, 5, 180, 'MEDIO', 3),

('Chai Latte', 'Bebida indiana especiada com leite. Aromatica e reconfortante.', 'Cha preto, leite, canela, cardamomo, gengibre, cravo, acucar', 'Ferva leite com especiarias. Adicione cha e deixe em infusao. Coe, adoce e sirva quente polvilhado com canela.', 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400', FALSE, 4, 15, 'FACIL', 6),

('Mille-feuille', 'Sobremesa francesa com massa folhada e creme. Elegante e classica.', 'Massa folhada, creme de confeiteiro, acucar de confeiteiro, baunilha', 'Asse camadas de massa folhada ate dourar. Monte intercalando com creme de confeiteiro. Finalize com acucar de confeiteiro polvilhado.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400', TRUE, 5, 120, 'DIFICIL', 1),

('Falafel', 'Bolinho arabe de grao de bico frito. Vegetariano e nutritivo.', 'Grao de bico, cebola, alho, salsinha, cominho, coentro, oleo para fritar', 'Deixe grao de bico de molho overnight. Moa com temperos sem adicionar agua. Modele bolinhos e frite em oleo quente ate dourar. Sirva com tahine.', 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400', FALSE, 4, 20, 'MEDIO', 4),

('Strudel de Maca', 'Torta austriaca folhada com macas. Delicada e aromatica.', 'Massa filo, macas, acucar, canela, passas, nozes, manteiga', 'Refogue macas com acucar e canela. Pincele camadas de massa filo com manteiga. Recheie com macas, nozes e passas. Enrole e asse ate dourar.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400', TRUE, 4, 60, 'MEDIO', 1),

('Borscht', 'Sopa eslava de beterraba. Colorida e nutritiva.', 'Beterraba, repolho, cebola, cenoura, caldo de carne, creme de leite azedo', 'Cozinhe beterraba ate amolecer. Refogue vegetais. Misture tudo com caldo e cozinhe ate sabores se integrarem. Sirva com creme azedo.', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400', FALSE, 3, 60, 'FACIL', 7),

('Brigadeiro Gourmet', 'Versao sofisticada do brigadeiro brasileiro. Elegante e irresistivel.', 'Chocolate belga, creme de leite fresco, manteiga, cacau em po premium', 'Derreta chocolate com creme de leite em banho-maria. Adicione manteiga e mexa ate brilhar. Deixe esfriar, modele bolinhas e passe em cacau premium.', 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400', TRUE, 5, 45, 'MEDIO', 1),

('Goulash Hungaro', 'Ensopado hungaro com paprica. Reconfortante e aromatico.', 'Carne bovina, cebola, paprica doce, tomate, pimentao, batata, caldo', 'Doure carne em cubos. Refogue cebola com paprica. Adicione carne, tomate, pimentao e caldo. Cozinhe por 2 horas. Adicione batatas nos ultimos 30 minutos.', 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400', FALSE, 4, 150, 'MEDIO', 3);
