CREATE DATABASE appetitedb;

\c appetitedb;

CREATE TABLE categorias (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL
);

CREATE TABLE receitas (
  id SERIAL PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  descricao TEXT,
  ingredientes TEXT,
  modo_preparo TEXT,
  imagem TEXT,
  favorita BOOLEAN DEFAULT FALSE,
  avaliacao INTEGER CHECK (avaliacao IS NULL OR (avaliacao >= 1 AND avaliacao <= 5)),
  tempo_preparo INTEGER,
  dificuldade VARCHAR(30) CHECK (dificuldade IN ('FACIL', 'MEDIO', 'DIFICIL')) NOT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  categoria_id INTEGER REFERENCES categorias(id) ON DELETE SET NULL,
  UNIQUE (titulo)
);

CREATE TABLE receita_categorias (
  receita_id INTEGER REFERENCES receitas(id) ON DELETE CASCADE,
  categoria_id INTEGER REFERENCES categorias(id) ON DELETE CASCADE,
  PRIMARY KEY (receita_id, categoria_id)
);

CREATE TABLE favoritos (
  id SERIAL PRIMARY KEY,
  receita_id INTEGER NOT NULL REFERENCES receitas(id) ON DELETE CASCADE,
  usuario_id INTEGER NOT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(receita_id, usuario_id)
);

CREATE INDEX idx_favoritos_usuario ON favoritos(usuario_id);
CREATE INDEX idx_favoritos_receita ON favoritos(receita_id);

INSERT INTO categorias (id, nome) VALUES 
(1, 'Sobremesas'),
(2, 'Lanches'),
(3, 'Diet'),
(4, 'Vegetariano'),
(5, 'Bebidas');

INSERT INTO receitas (titulo, descricao, ingredientes, modo_preparo, imagem, favorita, avaliacao, tempo_preparo, dificuldade, categoria_id) VALUES 
('Bolo de Cenoura', 'Bolo tradicional brasileiro, macio e umido, com uma deliciosa cobertura de chocolate que derrete na boca. Perfeito para o cafe da tarde.', '3 cenouras medias, 3 ovos, 1 xicara de oleo, 2 xicaras de acucar, 2 xicaras de farinha de trigo, 1 colher de sopa de fermento em po, 1 lata de leite condensado, 4 colheres de sopa de chocolate em po', 'Descasque e pique as cenouras. Bata no liquidificador as cenouras, ovos e oleo ate ficar homogeneo. Em uma tigela, misture o acucar, farinha e fermento. Adicione a mistura do liquidificador e mexa bem. Despeje em forma untada e asse a 180 graus por 40 minutos. Para a cobertura, misture leite condensado com chocolate em po e cozinhe ate engrossar. Espalhe sobre o bolo morno.', 'https://www.pennacchi.com.br/image/jpg/88c6d63ef0da572f933f07606d966227.jpg', TRUE, 5, 60, 'FACIL', 1),
('Pudim de Leite', 'Sobremesa classica cremosa com caramelo dourado. Uma receita tradicional que nunca sai de moda e encanta qualquer mesa.', '1 lata de leite condensado, 1 lata de leite, 3 ovos, 1 xicara de acucar para caramelo', 'Faca o caramelo derretendo o acucar em uma panela ate dourar. Despeje numa forma de pudim e gire para cobrir o fundo. No liquidificador, bata leite condensado, leite e ovos. Despeje sobre o caramelo. Asse em banho-maria a 180 graus por 1 hora. Deixe esfriar, geladeira por 4 horas e desenforme passando uma faca nas bordas.', 'https://www.receitasnestle.com.br/sites/default/files/srh_recipes/e33f558634f17b8197bd2ad4061cdaff.jpg', TRUE, 5, 90, 'MEDIO', 1),
('Brigadeiro', 'Doce brasileiro mais famoso, feito com leite condensado e chocolate. Irresistivel e perfeito para festas e comemoracoes.', '1 lata de leite condensado, 3 colheres de sopa de chocolate em po, 1 colher de sopa de manteiga, chocolate granulado para decorar', 'Em uma panela, misture leite condensado, chocolate em po e manteiga. Cozinhe em fogo baixo, mexendo sempre, ate desgrudar do fundo da panela (cerca de 15 minutos). Deixe esfriar, faca bolinhas com as maos untadas com manteiga e passe no chocolate granulado. Coloque em forminhas de papel.', 'https://www.seara.com.br/wp-content/uploads/2025/09/brigadeiro-sem-leite-condensado-portal-minha-receita.webp', TRUE, 5, 30, 'FACIL', 1),
('Macarrao a Carbonara', 'Prato italiano classico e elegante, com molho cremoso feito com ovos, queijo e bacon. Simplicidade e sabor em cada garfada.', '400g de espaguete, 200g de bacon, 4 gemas de ovos, 1 xicara de queijo parmesao ralado, sal e pimenta-do-reino a gosto', 'Cozinhe o macarrao em agua salgada ate ficar al dente. Frite o bacon ate ficar crocante. Em uma tigela, misture gemas com parmesao. Escorra o macarrao reservando 1 xicara da agua do cozimento. Misture o macarrao quente com bacon, retire do fogo e adicione a mistura de ovos, mexendo rapidamente. Adicione agua do cozimento se necessario. Tempere e sirva.', 'https://s2-receitas.glbimg.com/VyDAlpil2ZIBYMyXsWKkdcva6eA=/1366x0/filters:format(jpeg)/https://i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2024/Q/d/0fBS7KTNGBHQvkrOItyg/espaguete-a-carbonara.jpg', FALSE, 4, 25, 'FACIL', 2),
('Lasanha a Bolonhesa', 'Lasanha tradicional com molho bolonhesa rico e saboroso, intercalada com queijos cremosos. Perfeita para reunir a familia.', '500g de massa de lasanha, 500g de carne moida, 2 latas de molho de tomate, 500g de mucarela, 200g de presunto, molho branco, queijo parmesao', 'Prepare o molho refogando a carne com cebola e alho, adicione molho de tomate e temperos. Cozinhe a massa. Faca camadas alternando massa, molho bolonhesa, presunto, mucarela e molho branco. Repita as camadas, finalize com queijo parmesao e asse a 200 graus por 30 minutos ate dourar.', 'https://guiadacozinha.com.br/wp-content/uploads/2014/01/lasanha-bolonhesa-na-pressao.jpg', TRUE, 5, 90, 'MEDIO', 2),
('Nhoque de Batata', 'Massa italiana macia e saborosa, feita com batatas frescas. Acompanha perfeitamente molhos variados.', '1kg de batatas, 2 ovos, 300g de farinha de trigo, sal a gosto, molho de tomate para acompanhar', 'Cozinhe as batatas com casca ate ficarem macias. Descasque e amasse ainda quentes. Misture com ovos, sal e farinha aos poucos ate formar uma massa lisa. Faca rolinhos e corte pedacos pequenos. Passe os nhoques pelo garfo para fazer risquinhos. Cozinhe em agua fervente ate subirem a superficie. Sirva com molho de sua preferencia.', 'https://www.cozinhaaz.com/wp-content/uploads/2017/04/nhoque-de-batata-1-1024x640.jpg', FALSE, 4, 60, 'MEDIO', 2),
('Bife a Parmegiana', 'Classico bife empanado coberto com molho de tomate e queijo gratinado. Um prato que agrada toda a familia.', '4 bifes de alcatra, 2 ovos batidos, farinha de rosca, molho de tomate, mucarela fatiada, presunto, queijo parmesao', 'Bata os bifes para amaciá-los. Tempere com sal e pimenta. Passe na farinha, depois no ovo e na farinha de rosca. Frite ate dourar. Em um refratario, coloque os bifes, cubra com molho de tomate, presunto, mucarela e parmesao. Leve ao forno ate o queijo derreter e dourar.', 'https://img.saborosos.com.br/imagens/bife-a-parmegiana.jpg', TRUE, 5, 45, 'MEDIO', 3),
('Frango Assado', 'Frango inteiro temperado com ervas e especiarias, assado ate ficar dourado e suculento por fora, macio por dentro.', '1 frango inteiro, alho, limao, sal, pimenta, tomilho, alecrim, azeite, batatas para acompanhar', 'Limpe o frango e faca furos com uma faca. Prepare uma pasta com alho amassado, sal, pimenta, ervas e azeite. Esfregue bem o frango por dentro e por fora. Deixe marinar por 2 horas. Asse a 200 graus por 1 hora, regando com o proprio caldo. Sirva com batatas assadas.', 'https://i0.wp.com/espetinhodesucesso.com/wp-content/uploads/2025/04/Como-fazer-frango-assado-no-forno.jpg?resize=800%2C450&ssl=1', TRUE, 5, 120, 'MEDIO', 3),
('Feijoada', 'Prato tipico brasileiro, feito com feijao preto e carnes variadas. Tradicao e sabor que representa nossa cultura culinaria.', '500g de feijao preto, 300g de carne seca, 200g de linguica calabresa, 200g de costelinha de porco, temperos variados', 'Deixe o feijao de molho overnight. Cozinhe as carnes separadamente. Refogue cebola, alho e temperos, adicione o feijao escorrido e as carnes. Cubra com agua e cozinhe por 2 horas em fogo baixo, mexendo ocasionalmente. Sirva com arroz, couve refogada, laranja e farofa.', 'https://anamariabrogui.com.br/assets/uploads/receitas/fotos/bdbe9156f357a055b99450e76abad95e9f35d3cb.png', FALSE, 5, 180, 'DIFICIL', 3),
('Salada Caesar', 'Salada classica americana com alface crocante, croutons dourados e molho cremoso especial. Refrescante e saborosa.', 'Alface americana, croutons, queijo parmesao, molho caesar, anchovas (opcional)', 'Lave e pique a alface em pedacos grandes. Prepare croutons tostando cubos de pao com azeite e alho. Misture a alface com o molho caesar, adicione croutons e queijo parmesao lascado. Finalize com anchovas se desejar. Sirva imediatamente para manter a crocancia.', 'https://img.cybercook.com.br/receitas/441/salada-caesar-2.jpeg', FALSE, 4, 15, 'FACIL', 4),
('Quiche de Legumes', 'Torta francesa salgada com base crocante e recheio cremoso de legumes. Perfeita para almocos leves e nutritivos.', 'Massa quebrada, ovos, creme de leite, queijo, abobrinha, tomate, cebola, temperos', 'Prepare a massa e forre uma forma. Refogue os legumes picados. Misture ovos, creme de leite e queijo. Combine com os legumes refogados, tempere e despeje sobre a massa. Asse a 180 graus por 35 minutos ate dourar. Deixe esfriar um pouco antes de desenformar e servir.', 'https://canaldareceita.com.br/wp-content/uploads/2025/02/Quiche-de-Legumes.jpg', TRUE, 4, 50, 'MEDIO', 4),
('Hamburguer Artesanal', 'Hamburguer caseiro com carne suculenta e ingredientes frescos. Muito mais saboroso que os industrializados.', 'Carne moida, pao de hamburguer, alface, tomate, cebola, queijo, molhos especiais', 'Tempere a carne moida e faca hamburguers do tamanho desejado. Grelhe por 3-4 minutos de cada lado. Torre levemente o pao. Monte o hamburguer com alface, tomate, cebola, hamburguer, queijo e molhos. Sirva acompanhado de batatas fritas.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCoUhMnPmRh4ILmy00z6avGA5amn6L_eCCRg&s', TRUE, 5, 25, 'FACIL', 2),
('Coxinha', 'Salgado brasileiro tradicional com massa macia e recheio de frango temperado. Perfeita para festas e lanches.', 'Frango desfiado, massa de mandioca, temperos, farinha de rosca, ovos para empanar', 'Cozinhe e desfie o frango, tempere bem. Prepare a massa cozinhando agua com temperos e adicionando farinha aos poucos ate formar uma massa lisa. Modele as coxinhas com o recheio, passe no ovo e farinha de rosca. Frite em oleo quente ate dourar. Escorra em papel absorvente.', 'https://sabores-new.s3.amazonaws.com/public/2025/01/COXINHA-scaled.jpg', TRUE, 5, 60, 'MEDIO', 2),
('Pastel de Carne', 'Pastel crocante com recheio saboroso de carne temperada. Classico da culinaria brasileira.', 'Massa de pastel, carne moida, cebola, temperos, oleo para fritar', 'Refogue a carne moida com cebola e temperos ate secar. Abra a massa, coloque o recheio, feche bem as bordas com garfo. Frite em oleo bem quente ate dourar dos dois lados. Escorra e sirva quente, acompanhado de molho de pimenta.', 'https://assets.unileversolutions.com/recipes-v2/54541.jpg', FALSE, 4, 40, 'MEDIO', 2),
('Suco Detox', 'Bebida saudavel e refrescante, rica em vitaminas e minerais. Ideal para quem busca uma alimentacao equilibrada.', 'Couve, maca, limao, gengibre, agua de coco', 'Lave bem todos os ingredientes. Bata no liquidificador a couve, maca picada, suco de limao, gengibre e agua de coco ate ficar homogeneo. Coe se desejar uma textura mais lisa. Sirva gelado, preferencialmente logo apos o preparo para manter as propriedades nutricionais.', 'https://www.sabornamesa.com.br/media/k2/items/cache/52738552667e33eb1fba35383a2da217_XL.jpg', FALSE, 4, 10, 'FACIL', 5),
('Vitamina de Banana', 'Bebida cremosa e nutritiva, perfeita para o cafe da manha ou lanche da tarde. Rica em potassio e energia.', 'Bananas maduras, leite, mel, aveia (opcional)', 'Descasque as bananas e corte em rodelas. Bata no liquidificador com leite gelado e mel a gosto. Adicione aveia se desejar mais cremosidade e fibras. Bata ate ficar homogeneo e cremoso. Sirva imediatamente em copos gelados.', 'https://www.receiteria.com.br/wp-content/uploads/vitamina-de-banana-capa.jpg', TRUE, 5, 5, 'FACIL', 5),
('Caldo Verde', 'Sopa tradicional portuguesa, reconfortante e saborosa, perfeita para dias frios. Um classico que aquece o coracao.', 'Batatas, couve portuguesa, linguica calabresa, cebola, alho, azeite, sal', 'Refogue cebola e alho no azeite. Adicione batatas picadas e agua. Cozinhe ate as batatas ficarem macias e amasse levemente. Adicione a couve cortada bem fininha e a linguica em rodelas. Cozinhe por mais 5 minutos. Tempere e sirva quente com um fio de azeite por cima.', 'https://s2-receitas.glbimg.com/d51cHB7NuxyXBrEkCpp1aKrQixc=/0x0:1366x768/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2024/b/9/le3LrdQTu4r3xZvInLAA/caldo-verde-receita.jpg', TRUE, 5, 40, 'FACIL', 3),
('Sopa de Legumes', 'Sopa nutritiva e saudavel com variedade de legumes frescos. Reconfortante e perfeita para uma alimentacao equilibrada.', 'Cenoura, abobrinha, batata, chuchu, cebola, alho, temperos verdes', 'Refogue cebola e alho no azeite. Adicione todos os legumes picados e refogue por alguns minutos. Cubra com agua, tempere e cozinhe ate os legumes ficarem macios. Se desejar, bata parte da sopa no liquidificador para engrossar. Finalize com temperos verdes picados.', 'https://assets.unileversolutions.com/recipes-v2/36850.jpg', FALSE, 4, 35, 'FACIL', 3),
('Paella de Frutos do Mar', 'Prato espanhol tradicional com arroz temperado com acafrao e frutos do mar frescos. Sofisticado e cheio de sabor.', 'Arroz bomba, camaroes, lulas, mexilhoes, acafrao, tomate, pimentao, alho', 'Refogue alho, tomate e pimentao. Adicione o arroz e refogue. Acrescente caldo quente com acafrao aos poucos. Disponha os frutos do mar por cima sem mexer. Cozinhe em fogo baixo por 18 minutos. Deixe descansar antes de servir.', 'https://s2-receitas.glbimg.com/J3pMdPoxd2-lLW5u5Fe-TqYd6FQ=/1920x0/filters:format(jpeg)/https://i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2022/H/U/cK5n3IT6ACcbda2FBBNA/paella-de-frutos-do-mar.jpg', FALSE, 5, 45, 'DIFICIL', 3),
('Risoto de Camarao', 'Risoto cremoso italiano com camaroes suculentos. Prato elegante e sofisticado para ocasioes especiais.', 'Arroz arboreo, camaroes, caldo de peixe, vinho branco, cebola, queijo parmesao', 'Refogue cebola ate transparente. Adicione o arroz e torre levemente. Acrescente vinho branco e deixe evaporar. Adicione caldo quente uma concha de cada vez, mexendo sempre. Nos ultimos minutos, adicione camaroes e queijo parmesao. Sirva imediatamente.', 'https://s2-receitas.glbimg.com/KWpGf7SHzNbPSab_Z3fmhDOGCmo=/0x0:1080x608/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_e84042ef78cb4708aeebdf1c68c6cbd6/internal_photos/bs/2022/A/5/RQBWn4SlyzO0JWxYflwg/capa-materia-gshow-102-.png', TRUE, 5, 40, 'MEDIO', 2),
('Strogonoff de Carne', 'Prato russo adaptado ao paladar brasileiro, cremoso e saboroso. Acompanha perfeitamente arroz e batata palha.', 'File mignon em tiras, champignons, creme de leite, molho de tomate, mostarda, conhaque', 'Doure a carne em panela quente. Reserve. Na mesma panela, refogue champignons. Adicione molho de tomate, mostarda e creme de leite. Retorne a carne, adicione conhaque e deixe apurar. Tempere e sirva com arroz branco e batata palha.', 'https://receitatodahora.com.br/wp-content/uploads/2022/09/estrogonofe-de-carne-cremoso.jpg', TRUE, 5, 30, 'FACIL', 3),
('Escondidinho de Carne Seca', 'Prato tipico nordestino com pure de mandioca cremoso cobrindo carne seca saborosa. Conforto em cada colherada.', 'Carne seca, mandioca, queijo coalho, cebola, alho, leite, manteiga', 'Cozinhe e desfie a carne seca, refogue com cebola e alho. Cozinhe a mandioca, amasse com leite e manteiga ate formar um pure. Em refratario, faca camadas de carne e pure, finalize com queijo. Asse ate dourar por cima.', 'https://guiadacozinha.com.br/wp-content/uploads/2020/11/escondidinho-de-frigideira-1.jpg', FALSE, 4, 60, 'MEDIO', 3),
('Moqueca de Peixe', 'Prato baiano tradicional com peixe cozido em leite de coco e dende. Sabores intensos da culinaria regional.', 'Peixe em postas, leite de coco, dende, tomate, cebola, pimentao, coentro', 'Tempere o peixe e deixe marinar. Refogue cebola, tomate e pimentao. Adicione leite de coco e dende, tempere. Coloque o peixe e cozinhe por 15 minutos sem mexer muito. Finalize com coentro. Sirva com arroz branco e pirao.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCrtdMwfrgRU0HBEPZhPdCNyHuyrx8JUzcIA&s', FALSE, 5, 35, 'MEDIO', 3),
('Bobo de Camarao', 'Prato tipico baiano cremoso feito com mandioca e camaroes. Sabor unico da culinaria afro-brasileira.', 'Camaroes, mandioca, leite de coco, dende, cebola, alho, temperos', 'Cozinhe a mandioca e bata com leite de coco ate formar um creme. Refogue camaroes com temperos. Misture o creme de mandioca com camaroes, adicione dende e tempere. Cozinhe ate encorpar. Sirva quente com arroz.', 'https://sabores-new.s3.amazonaws.com/public/2024/11/bobo-de-camarao-rapido.jpg', TRUE, 5, 45, 'MEDIO', 3),
('Mousse de Chocolate', 'Sobremesa francesa classica, leve e aerada, com sabor intenso de chocolate. Elegante e irresistivel.', 'Chocolate meio amargo, ovos, acucar, creme de leite fresco', 'Derreta o chocolate em banho-maria. Separe claras e gemas. Bata as gemas com acucar ate clarear. Misture com chocolate morno. Bata claras em neve e creme de leite separadamente. Incorpore delicadamente ao chocolate. Leve a geladeira por 4 horas.', 'https://img.youtube.com/vi/rG1osb8STH0/maxresdefault.jpg', TRUE, 5, 20, 'MEDIO', 1),
('Torta de Limao', 'Torta refrescante com base crocante e creme de limao azedinho. Perfeita para finalizar refeicoes pesadas.', 'Biscoito triturado, manteiga, leite condensado, suco de limao, creme de leite, gelatina incolor', 'Misture biscoito triturado com manteiga derretida, forre forma e leve ao freezer. Misture leite condensado, suco de limao e gelatina dissolvida. Adicione creme de leite batido. Despeje sobre a base e geladeira por 4 horas.', 'https://www.receitasnestle.com.br/sites/default/files/styles/recipe_detail_desktop_new/public/srh_recipes/aa75ade839f233e8d746e774e80b0f37.jpg?itok=ajIqZUek', FALSE, 4, 30, 'FACIL', 1),
('Sorvete de Morango', 'Sorvete cremoso caseiro com morangos frescos. Sobremesa refrescante e natural para os dias quentes.', 'Morangos, acucar, creme de leite, leite condensado', 'Bata morangos com acucar ate formar uma polpa. Misture com creme de leite e leite condensado. Despeje em forma e congele por 2 horas. Retire, bata novamente e congele ate endurecer. Sirva em tacas geladas.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbxXgmRyNhE7r-6umOBKkzFZKigatBDUqZEg&s', TRUE, 5, 15, 'FACIL', 1),
('Pave de Chocolate', 'Sobremesa em camadas com biscoitos e creme de chocolate. Classica e sempre presente nas mesas brasileiras.', 'Biscoito champagne, leite, chocolate em po, leite condensado, creme de leite, manteiga', 'Prepare um creme cozinhando leite condensado, chocolate e manteiga. Deixe esfriar e misture com creme de leite batido. Molhe biscoitos no leite e monte camadas alternando biscoito e creme. Finalize com chocolate ralado. Geladeira overnight.', 'https://assets.unileversolutions.com/recipes-v2/206185.jpg', TRUE, 5, 30, 'FACIL', 1),
('Banoffee Pie', 'Torta inglesa com base de biscoito, doce de leite, banana e chantilly. Combinacao perfeita de sabores.', 'Biscoito triturado, manteiga, doce de leite, bananas, chantilly, chocolate para decorar', 'Misture biscoito com manteiga, forre forma e leve ao forno rapidamente. Espalhe doce de leite sobre a base fria, disponha fatias de banana. Cubra com chantilly e decore com chocolate ralado. Sirva gelada.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEkh86oiF2S3SVqOsBCg5tUG8wH_bINNNQBw&s', FALSE, 4, 25, 'FACIL', 1),
('Caipirinha', 'Drink brasileiro mais famoso mundialmente, refrescante e com sabor marcante da cachaca com limao.', 'Cachaca, limao, acucar, gelo', 'Corte o limao em pedacos pequenos. Em um copo, macere o limao com acucar usando um socador. Adicione gelo e cachaca. Misture bem e sirva imediatamente. Decore com uma fatia de limao.', 'https://receitinhasdemae.com.br/wp-content/uploads/2024/09/caipirinha-de-limao.jpg.webp', FALSE, 5, 5, 'FACIL', 5),
('Smoothie Verde', 'Bebida saudavel com vegetais verdes e frutas. Rica em nutrientes e perfeita para comecar o dia com energia.', 'Espinafre, banana, maca verde, agua de coco, hortela', 'Lave bem o espinafre e hortela. Bata todos os ingredientes no liquidificador ate ficar homogeneo e cremoso. Se necessario, adicione mais agua de coco. Sirva imediatamente em copos gelados.', 'https://keto-mojo.com/wp-content/uploads/2020/04/Keto-Green-Smoothie-1.jpg', FALSE, 4, 8, 'FACIL', 5),
('Mojito', 'Drink cubano refrescante com hortela, limao e rum. Perfeito para dias quentes e momentos descontraidos.', 'Rum branco, hortela fresca, limao, acucar, agua com gas, gelo', 'Em um copo, macere delicadamente as folhas de hortela com acucar e suco de limao. Adicione gelo, rum e complete com agua com gas. Misture suavemente e decore com ramo de hortela.', 'https://lovefoodfeed.com/wp-content/uploads/2023/10/Mojito-cocktail-1200-06-768x768.jpg', TRUE, 5, 10, 'FACIL', 5),
('Gazpacho', 'Sopa fria espanhola com tomates frescos e vegetais. Refrescante e perfeita para dias quentes de verao.', 'Tomates maduros, pepino, pimentao, cebola, alho, azeite, vinagre, pao', 'Pique todos os vegetais. Molhe fatias de pao em agua. Bata tudo no liquidificador com azeite e vinagre ate ficar homogeneo. Tempere, coe se desejar e leve a geladeira. Sirva bem gelado.', 'https://www.allrecipes.com/thmb/4OQBqI3tsH6kV320BJDy1qdY10Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/222331-Chef-Johns-Gazpacho-ddmfs-2x1-2783-32ea8c762964424a94b5c557134a259c.jpg', FALSE, 4, 20, 'FACIL', 4),
('Tapioca Doce', 'Lanche brasileiro feito com goma de tapioca e recheios doces. Sem gluten e muito saborosa.', 'Goma de tapioca, leite condensado, coco ralado, queijo coalho', 'Hidrate a goma de tapioca ate ficar umida. Em frigideira antiaderente, espalhe a goma formando uma panqueca. Quando comecar a grudar, adicione o recheio doce de um lado, dobre ao meio e sirva quente.', 'https://i.pinimg.com/736x/01/86/6b/01866b9c1a1546c3d82b5d90dfcf2694.jpg', TRUE, 4, 10, 'FACIL', 1),
('Empadao de Frango', 'Torta salgada grande com massa crocante e recheio generoso de frango. Perfeita para almocos em familia.', 'Farinha, manteiga, ovos, frango desfiado, palmito, ervilha, molho branco', 'Prepare a massa misturando farinha, manteiga e ovos. Forre uma forma grande. Misture frango desfiado com palmito, ervilha e molho branco. Recheie a torta, cubra com massa e asse ate dourar.', 'https://i.ytimg.com/vi/F2npcDqkY5g/maxresdefault.jpg', FALSE, 4, 80, 'MEDIO', 2),
('Esfirra de Carne', 'Salgado arabe com massa macia e recheio temperado de carne. Tradicao da culinaria sirio-libanesa.', 'Farinha, fermento, carne moida, cebola, temperos arabes, azeite', 'Prepare a massa com farinha, fermento e agua morna. Deixe crescer. Refogue carne moida com cebola e temperos arabes. Abra a massa, recheie e modele as esfirras. Asse ate dourar.', 'https://s2-receitas.glbimg.com/KEQ-ZKguwDiFCvG7ns3dfcnpxqs=/0x0:1366x768/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2025/6/i/z2mrzpRXSuGOzSUMEjyg/esfiha-de-carne-moida-receita.jpg', TRUE, 5, 70, 'MEDIO', 2),
('Quibe Frito', 'Salgado arabe crocante por fora e macio por dentro, com recheio de carne temperada. Muito popular no Brasil.', 'Trigo para quibe, carne moida, cebola, temperos arabes, hortela', 'Hidrate o trigo para quibe. Misture com parte da carne e temperos para formar a massa. Refogue o restante da carne para o recheio. Modele os quibes, recheie e frite em oleo quente ate dourar.', 'https://www.yoki.com.br/_next/image?url=https%3A%2F%2Fprodcontent.yoki.com.br%2Fwp-content%2Fuploads%2F2024%2F09%2FKibe-tradicional-6016x4016-1.jpg&w=1400&q=75', TRUE, 5, 60, 'MEDIO', 2 ),
('Wrap de Frango', 'Sanduiche enrolado em tortilha com frango grelhado e vegetais frescos. Opcao saudavel e pratica.', 'Tortilha, peito de frango, alface, tomate, cenoura, molho iogurte', 'Grelhe o frango temperado ate cozinhar completamente. Corte em tiras. Aqueça a tortilha, recheie com frango, vegetais frescos e molho. Enrole firmemente e corte ao meio para servir.', 'https://minhasreceitinhas.com.br/wp-content/uploads/2023/05/Wrap-de-frango-com-Rap10-1024x576.jpg', FALSE, 4, 20, 'FACIL', 2),
('Cafe Gelado', 'Bebida refrescante com cafe forte e gelo, perfeita para dias quentes. Energizante e deliciosa.', 'Cafe forte, acucar, gelo, leite (opcional)', 'Prepare um cafe forte e doce enquanto quente. Deixe esfriar completamente. Sirva em copos com bastante gelo. Adicione leite se desejar um cafe mais suave. Decore com canela em po.', 'https://static.itdg.com.br/images/1200-630/efb5ad7c42f081c11ca5cfe8fae97a67/cafe-gelado.jpg', FALSE, 4, 15, 'FACIL', 5),
('Cha Gelado de Frutas', 'Bebida refrescante e saudavel com cha e frutas naturais. Hidratante e cheia de sabor.', 'Cha preto, frutas vermelhas, limao, hortela, mel', 'Prepare o cha e deixe esfriar. Adicione frutas vermelhas, fatias de limao e mel a gosto. Deixe na geladeira por 2 horas para as frutas soltarem sabor. Sirva com gelo e hortela.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9BaluAk5ocbZVpJmBo8AdW82HTxp8HwnE2Q&s', TRUE, 4, 10, 'FACIL', 5),
('Vitamina de Abacate', 'Bebida cremosa brasileira doce feita com abacate. Rica e nutritiva, perfeita para lanches.', 'Abacate maduro, leite, acucar, leite condensado (opcional)', 'Retire a polpa do abacate maduro. Bata no liquidificador com leite gelado e acucar ate ficar cremoso. Adicione leite condensado se desejar mais doce. Sirva imediatamente em copos gelados.', 'https://receitadaboa.com.br/wp-content/uploads/2024/04/iStock-511024538.jpg', TRUE, 5, 8, 'FACIL', 5),
('Biscoito de Polvilho', 'Biscoito brasileiro crocante e sem gluten, feito com polvilho. Perfeito para acompanhar cafe.', 'Polvilho doce, polvilho azedo, ovos, oleo, queijo ralado', 'Misture os polvilhos com ovos batidos, oleo quente e queijo. Amasse bem ate formar uma massa lisa. Modele biscoitinhos pequenos e asse em forno pre-aquecido ate dourar e ficar crocante.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgrnKUmfvqSHeq7bWw1naHEWiV1nQlBpjI1A&s', FALSE, 4, 35, 'FACIL', 1),
('Panqueca Americana', 'Panquecas fofas e doces servidas com mel e frutas. Cafe da manha especial e reconfortante.', 'Farinha de trigo, acucar, fermento em po, ovos, leite, manteiga derretida, mel, frutas vermelhas', 'Misture ingredientes secos. A parte, bata ovos com leite e manteiga. Combine tudo delicadamente. Faca panquecas na frigideira. Sirva empilhadas com mel e frutas.', 'https://static.itdg.com.br/images/360-240/34e48b244df56bb8c516375eb418ed45/panqueca-americana.jpg', FALSE, 5, 25, 'FACIL', 1),
('Guacamole', 'Pasta mexicana cremosa de abacate com temperos. Perfeita para acompanhar nachos ou como entrada.', 'Abacates maduros, limao, cebola roxa, tomate, coentro, jalapeno, sal, azeite', 'Amasse abacates com garfo deixando pedacos pequenos. Adicione cebola, tomate e jalapeno picados. Tempere com limao, sal e coentro. Sirva com tortilhas.', 'https://www.foodandwine.com/thmb/PaNa5IByv6syP1U3s3mHuN_BK2c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/guacamole-for-a-crowd-FT-RECIPE0125-624c884187d44062ae4fb86794d0769c.jpeg', TRUE, 4, 15, 'FACIL', 4),
('Salada de Quinoa', 'Salada nutritiva e colorida com quinoa, legumes frescos e molho citrico. Opcao saudavel e saborosa.', 'Quinoa, tomate cereja, pepino, cenoura, rucula, azeite, limao, sal, pimenta', 'Cozinhe quinoa ate ficar macia. Deixe esfriar. Pique todos os legumes. Misture quinoa com vegetais. Tempere com azeite, limao, sal e pimenta. Sirva gelada.', 'https://canaldareceita.com.br/wp-content/uploads/2025/08/Salada-de-Quinoa-com-Frango-Grelhado-e-Legumes.jpg', FALSE, 3, 20, 'FACIL', 4),
('Falafel', 'Bolinho arabe de grao de bico frito. Vegetariano e nutritivo.', 'Grao de bico, cebola, alho, salsinha, cominho, coentro, oleo para fritar', 'Deixe grao de bico de molho overnight. Moa com temperos sem adicionar agua. Modele bolinhos e frite em oleo quente ate dourar. Sirva com tahine.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaW8QPucti-WQBb67ko8l-Q3-yYSqnlapyVg&s', FALSE, 4, 20, 'MEDIO', 4),
('Ratatouille', 'Guisado frances de vegetais coloridos. Prato vegetariano tradicional da Provenca francesa.', 'Berinjela, abobrinha, pimentao, tomate, cebola, alho, ervas de provence, azeite', 'Corte todos vegetais em cubos uniformes. Refogue cada um separadamente. Combine numa panela com ervas e deixe cozinhar lentamente ate ficarem macios.', 'https://www.kikkoman.pt/fileadmin/_processed_/1/8/csm_1075-recipe-page-Saffron-scented-Ratatouille_desktop_5ddfe5fdbf.jpg', FALSE, 4, 55, 'MEDIO', 4),
('Milkshake de Morango', 'Bebida cremosa e doce com morangos frescos e sorvete. Refrescante e nostalgica.', 'Morangos frescos, sorvete de baunilha, leite, acucar, chantilly para decorar', 'Bata morangos com sorvete, leite e acucar ate ficar cremoso. Sirva em copos altos decorados com chantilly e morango inteiro.', 'https://media.istockphoto.com/id/576740204/pt/foto/batido-de-morango.jpg?s=612x612&w=0&k=20&c=dsqG3jX2VR-pcX7kWlKgIfUbiCHeq_Th2MZ6bttxnwI=', TRUE, 5, 8, 'FACIL', 5),
('Tiramisu', 'Sobremesa italiana classica com cafe, mascarpone e biscoitos. Elegante e irresistivel para os amantes de cafe.', 'Biscoito champagne, cafe forte, mascarpone, ovos, acucar, cacau em po, amaretto', 'Prepare cafe forte e deixe esfriar. Misture gemas com acucar, adicione mascarpone. Bata claras em neve e incorpore. Monte camadas de biscoito molhado no cafe e creme. Refrigere overnight e polvilhe cacau.', 'https://www.giallozafferano.com.br/images/5-598/Tiramisu_1200x800.jpg', FALSE, 4, 30, 'MEDIO', 1),
('Pao de Acucar', 'Pao doce tradicional com canela e acucar. Perfeito para o cafe da manha ou lanche da tarde.', 'Farinha de trigo, fermento biologico, acucar, ovos, manteiga, leite, canela, sal', 'Dissolva fermento no leite morno. Misture farinha, acucar e sal. Adicione ovos, manteiga e leite com fermento. Sove ate ficar lisa. Deixe crescer, modele e asse ate dourar.', 'https://s2-receitas.glbimg.com/NI-d1xcE2JQXdurQius71pp7ntI=/1280x0/filters:format(jpeg)/https://i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2022/4/4/jnZplhTOCP79CrWAuW4g/pao-doce-facil-receita.jpg', TRUE, 4, 180, 'DIFICIL', 1),
('Brownie de Chocolate', 'Brownie americano denso e chocolatudo. Sobremesa irresistivel para os amantes de chocolate.', 'Chocolate amargo, manteiga, acucar, ovos, farinha de trigo, nozes, essencia de baunilha', 'Derreta chocolate com manteiga. Bata ovos com acucar. Misture chocolate derretido, farinha e nozes. Asse em forma untada ate formar casquinha por cima.', 'https://moinhoglobo.com.br/wp-content/uploads/2016/02/51-Brownie-scaled.jpg', TRUE, 5, 45, 'FACIL', 1),
('Cheesecake de Frutas Vermelhas', 'Torta americana cremosa com base de biscoito e cobertura de frutas. Sobremesa elegante e saborosa.', 'Cream cheese, biscoito triturado, manteiga, acucar, ovos, frutas vermelhas, gelatina', 'Misture biscoito com manteiga para a base. Bata cream cheese com acucar e ovos. Despeje sobre base e asse em banho-maria. Decore com frutas vermelhas e gelatina.', 'https://revistasaboresdosul.com.br/wp-content/uploads/2016/07/cheesecake-de-frutas-vermelhas.jpg', FALSE, 4, 120, 'DIFICIL', 1),
('Tacos Mexicanos', 'Tortilhas mexicanas recheadas com carne temperada e acompanhamentos frescos. Sabor autentico do Mexico.', 'Tortilhas de milho, carne moida, cebola, pimentao, tomate, alface, queijo, molho picante', 'Tempere e refogue a carne com vegetais e especiarias mexicanas. Aqueça tortilhas. Monte tacos com carne, vegetais frescos, queijo e molho. Sirva imediatamente.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoAUBT5fxna3izc3u2Ev8LbQaIMXFxElv39Q&s', TRUE, 4, 30, 'FACIL', 2),
('Salada Grega', 'Salada mediterranea fresca com queijo feta e azeitonas. Saudavel e cheia de sabor mediterraneo.', 'Tomate, pepino, cebola roxa, azeitonas kalamata, queijo feta, azeite, oregano, limao', 'Corte tomates e pepinos em pedacos grandes. Adicione cebola em fatias, azeitonas e feta em cubos. Tempere com azeite, limao e oregano.', 'https://www.estadao.com.br/resizer/xgbdreke8bix84U4ILBWMO_KuX0=/arc-anglerfish-arc2-prod-estadao/public/3K45SRWMQBAMHEOCORS3HY2W5I.jpg', TRUE, 4, 12, 'FACIL', 4),
('Fish and Chips', 'Prato ingles tradicional com peixe empanado crocante e batatas fritas. Classico da culinaria britanica.', 'File de peixe branco, farinha, cerveja, batatas, oleo para fritar, sal, vinagre de malte', 'Prepare massa com farinha e cerveja. Corte batatas em fatias grossas e frite. Passe peixe na massa e frite ate dourar. Sirva quente com batatas e vinagre de malte.', 'https://dinnerthendessert.com/wp-content/uploads/2024/02/fish-and-chips-1x1-1.jpg', TRUE, 4, 40, 'MEDIO', 3),
('Crepe Suzette', 'Crepe frances flamejado com molho de laranja e licor. Sobremesa classica e espetacular.', 'Farinha, ovos, leite, manteiga, laranja, acucar, conhaque, Grand Marnier', 'Prepare massa de crepe fina. Faca crepes e reserve. Prepare molho com suco de laranja, acucar e licor. Flameje e sirva sobre os crepes dobrados.', 'https://guiadacozinha.com.br/wp-content/uploads/2019/10/crepe-suzette-receita-768x619.jpg', FALSE, 3, 45, 'DIFICIL', 1),
('Dim Sum Variado', 'Salgadinhos chineses no vapor. Tradicionais e delicados.', 'Massa de dumpling, camarao, porco moido, cebolinha, gengibre, molho shoyu', 'Prepare recheio misturando carnes com temperos. Abra massa fininha, recheie e modele. Cozinhe no vapor por 15 minutos. Sirva com molho de soja.', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/69/01/fb/classic-big-style-shrimp.jpg', FALSE, 4, 45, 'DIFICIL', 3),
('Kouign-Amann', 'Doce bretao folhado com caramelo. Crocante por fora, macio por dentro.', 'Farinha, fermento, manteiga salgada, acucar cristal', 'Prepare massa de pao. Incorpore manteiga em camadas como croissant. Adicione acucar entre dobras. Modele e asse ate caramelizar e dourar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQiXkL4IHh6-IEc_BkVQs1UycRTk7Vlj_-2Q&s', FALSE, 5, 240, 'DIFICIL', 1),
('Pozole Verde', 'Sopa mexicana tradicional com milho e carne. Festiva e nutritiva.', 'Milho pozole, porco, tomatillos, jalapenos, coentro, alface, rabanete', 'Cozinhe porco ate amolecer. Bata tomatillos com jalapenos. Misture com carne e milho. Cozinhe ate espessar. Sirva com acompanhamentos frescos.', 'https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480_1_5x/img/recipe/ras/Assets/2c449c2f03227e48a2dec072bc191522/Derivates/973050e1e27d5d12fd2fe81b481bbbc400f28068.jpg', TRUE, 4, 120, 'MEDIO', 3),
('Souvlaki', 'Espetinho grego de carne marinada. Aromatico e suculento.', 'Carne de porco, azeite, limao, oregano, alho, pao pita, tzatziki', 'Marine carne cortada em cubos com azeite, limao e temperos por 4 horas. Espete e grelhe ate dourar. Sirva com pita e tzatziki.', 'https://www.allrecipes.com/thmb/_8nS4xBO9sGYJgHCKID0V-Yo_jA=/0x512/filters:no_upscale():max_bytes(150000):strip_icc()/14713-souvlaki-ddmfs-Beauty-3x4-06471d380b394255a7716405c4ec0a22.jpg', FALSE, 4, 30, 'FACIL', 3),
('Trifle Ingles', 'Sobremesa em camadas com frutas e creme. Vistosa e deliciosa.', 'Pao de lo, frutas vermelhas, creme ingles, chantilly, geleia, sherry', 'Monte camadas de pao de lo embebido em sherry, frutas, geleia, creme ingles e chantilly. Repita camadas e finalize com frutas. Geladeira por 4 horas.', 'https://rms-media-prod.generalmills.com/17748cd3-6ab0-44aa-b753-2f8602addaee.jpg', TRUE, 4, 30, 'MEDIO', 1),
('Pancit Canton', 'Macarrao filipino salteado com vegetais. Colorido e saboroso.', 'Macarrao canton, frango, camarao, repolho, cenoura, molho de soja, calamansi', 'Hidrate macarrao. Salteie carnes, adicione vegetais e macarrao. Tempere com molhos e misture bem ate aquecer. Sirva com calamansi.', 'https://images.yummy.ph/yummy/uploads/2020/01/vegetablepancitrecipe1-3.jpg', FALSE, 4, 25, 'FACIL', 2),
('Couscous Marroquino', 'Semola marroquina com vegetais e especiarias. Aromatico e nutritivo.', 'Couscous, vegetais variados, grao de bico, especiarias, caldo de legumes', 'Hidrate couscous com caldo quente. Cozinhe vegetais com especiarias em tagine. Sirva couscous com legumes por cima e caldo a parte.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE_h8Tla0c76dMRnncGOcSXZlp68JVL29f9w&s', TRUE, 4, 45, 'MEDIO', 4),
('Pretzels Alemaes', 'Paes alemaes tradicionalmente salgados e macios. Classicos da Baviera.', 'Farinha, fermento, sal, bicarbonato, sal grosso para polvilhar', 'Prepare massa de pao. Modele pretzels. Ferva agua com bicarbonato e mergulhe pretzels rapidamente. Asse polvilhados com sal grosso ate dourar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS68s675I-4TXjn_0ZaRI5mpncP8QlhU22CSg&s', FALSE, 4, 180, 'MEDIO', 1),
('Arepas Venezuelanas', 'Paes de milho venezuelanos recheados. Versateis e nutritivos.', 'Farinha de milho pre-cozida, agua, sal, recheios variados', 'Misture farinha com agua salgada ate formar massa homogenea. Modele discos e asse em chapa ate formar casquinha. Abra e recheie a gosto.', 'https://cdn0.umcomo.com.br/pt/posts/6/1/9/como_fazer_arepas_venezuelanas_13916_paso_6_600.jpg', TRUE, 4, 20, 'FACIL', 3),
('Bubble Tea', 'Cha taiwanes com bolinhas de tapioca. Divertido e refrescante.', 'Cha preto, leite, acucar, bolinhas de tapioca, gelo', 'Cozinhe bolinhas de tapioca ate ficarem translucidas. Prepare cha doce e deixe esfriar. Misture com leite, adicione bolinhas no fundo do copo e sirva com canudo grosso.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUQeebnP0wQZHm3BwyZ5U_NpO3sxmRmLpTvQ&s', FALSE, 4, 30, 'FACIL', 5),
('Agua Saborizada com Frutas', 'Agua refrescante com frutas naturais. Hidratante e saudavel.', 'Agua filtrada, frutas variadas, gelo, mel', 'Pique frutas. Coloque em jarra com agua. Deixe gelar 2 horas. Sirva com gelo.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFl2pkkA4Emzz7CSDzZ-LI7wDLFv63U-734g&s', TRUE, 3, 10, 'FACIL', 5),
('Agua com Menta', 'Agua aromatizada com menta. Refrescante e digestiva.', 'Agua filtrada, folhas de menta fresca, limao, gelo, mel', 'Amasse menta levemente. Coloque em jarra com agua. Deixe gelar. Sirva com limao e gelo.', 'https://images.cookforyourlife.org/wp-content/uploads/2018/08/shutterstock_263972897-min.jpg', FALSE, 3, 10, 'FACIL', 5),
('Petit Gateau', 'Bolinho de chocolate com centro derretido. Sobremesa sofisticada que impressiona qualquer convidado.', 'Chocolate meio amargo, manteiga, ovos, acucar, farinha de trigo, sorvete de baunilha', 'Derreta chocolate com manteiga. Bata ovos com acucar ate dobrar de volume. Misture com chocolate e adicione farinha. Despeje em forminhas untadas e asse por 12 minutos a 200 graus. Desenforme e sirva com sorvete.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpetitgateau', TRUE, 5, 25, 'MEDIO', 1),

('Romeu e Julieta', 'Sobremesa brasileira classica com queijo minas e goiabada. Combinacao perfeita de sabores.', 'Queijo minas frescal, goiabada cascao, biscoito agua e sal', 'Corte o queijo e a goiabada em fatias de espessura igual. Monte intercalando queijo e goiabada. Sirva com biscoitos ou como sobremesa simples.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQromeujulieta', FALSE, 4, 10, 'FACIL', 1),

('Beijinho', 'Docinho brasileiro de coco, tradicional em festas. Irresistivel e facil de fazer.', 'Leite condensado, coco ralado, manteiga, acucar cristal, cravo para decorar', 'Misture leite condensado, coco e manteiga em panela. Cozinhe em fogo baixo mexendo sempre ate desgrudar do fundo. Deixe esfriar, faca bolinhas e passe no acucar. Decore com cravo.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbeijinho', TRUE, 5, 25, 'FACIL', 1),

('Cocada', 'Doce tradicional brasileiro de coco caramelizado. Sabor tropical em cada mordida.', 'Coco ralado fresco, acucar, agua, cravo, canela', 'Faca calda com acucar e agua. Adicione coco, cravo e canela. Cozinhe mexendo ate o ponto de soltar do fundo. Despeje em forma untada e corte em pedacos.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcocada', FALSE, 4, 40, 'FACIL', 1),

('Churros', 'Doce espanhol frito com recheio de doce de leite. Crocante por fora, macio por dentro.', 'Agua, manteiga, farinha de trigo, ovos, acucar, canela, doce de leite', 'Ferva agua com manteiga. Adicione farinha de uma vez e mexa ate formar bola. Adicione ovos um a um. Frite em formato alongado. Passe em acucar com canela e recheie com doce de leite.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQchurros', TRUE, 5, 35, 'MEDIO', 1),

('Quindim', 'Doce portugues de origem africana, brilhante e cremoso. Sabor marcante de coco e gemas.', 'Gemas de ovo, acucar, coco ralado, manteiga', 'Bata gemas com acucar ate clarear. Adicione coco e manteiga derretida. Despeje em forminhas untadas. Asse em banho-maria por 40 minutos ate dourar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQquindim', TRUE, 5, 60, 'MEDIO', 1),

('Creme Brulee', 'Sobremesa francesa com creme aveludado e crosta de caramelo crocante. Elegancia em cada colherada.', 'Creme de leite fresco, gemas, acucar, baunilha', 'Aqueca creme com baunilha. Bata gemas com acucar. Misture lentamente. Despeje em ramekins e asse em banho-maria. Refrigere e queime acucar por cima antes de servir.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcremebrulee', FALSE, 5, 50, 'DIFICIL', 1),

('Bolo de Fuba', 'Bolo tradicional brasileiro com sabor de fazenda. Textura rustica e sabor aconchegante.', 'Fuba, farinha de trigo, ovos, acucar, leite, oleo, queijo ralado, erva-doce', 'Bata ovos com acucar. Adicione leite e oleo. Misture fuba, farinha, queijo e erva-doce. Despeje em forma untada e asse por 40 minutos a 180 graus.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbolofuba', TRUE, 4, 50, 'FACIL', 1),

('Bauru', 'Sanduiche brasileiro classico com queijo derretido. Criado em Sao Paulo, conquistou o Brasil.', 'Pao frances, queijo mucarela, presunto, tomate, oregano, azeite', 'Corte o pao ao meio. Recheie com presunto e queijo. Leve ao forno ate derreter. Adicione tomate, oregano e azeite. Sirva quente.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbauru', FALSE, 4, 15, 'FACIL', 2),

('Pao de Queijo', 'Tradicional mineiro, macio por dentro e crocante por fora. Impossivel comer so um.', 'Polvilho azedo, leite, oleo, ovos, queijo minas curado, sal', 'Ferva leite com oleo e sal. Despeje sobre polvilho e misture. Quando morno, adicione ovos e queijo. Modele bolinhas e asse ate dourar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpaodequeijo', TRUE, 5, 35, 'FACIL', 2),

('Empada de Palmito', 'Salgado brasileiro com massa amanteigada e recheio cremoso. Perfeito para festas.', 'Farinha, manteiga, ovos, palmito, creme de leite, temperos', 'Prepare massa com farinha, manteiga e ovos. Forre forminhas. Misture palmito picado com creme e temperos. Recheie, cubra e asse ate dourar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQempadapalmito', TRUE, 4, 60, 'MEDIO', 2),

('Hot Dog Completo', 'Cachorro-quente brasileiro com todos os acompanhamentos. Refeicao completa e saborosa.', 'Pao de hot dog, salsicha, pure de batata, milho, ervilha, batata palha, molhos', 'Cozinhe salsichas. Aqueca paes. Monte com salsicha, pure, milho, ervilha, batata palha e molhos diversos. Sirva quente.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhotdog', TRUE, 5, 20, 'FACIL', 2),

('Sanduiche Natural', 'Opcao leve e saudavel para lanches rapidos. Refrescante e nutritivo.', 'Pao integral, frango desfiado, cenoura ralada, milho, maionese light, alface', 'Misture frango com cenoura, milho e maionese. Recheie o pao com a mistura e alface. Sirva gelado.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsanduichenatural', FALSE, 4, 15, 'FACIL', 2),

('Bruschetta', 'Entrada italiana com tomates frescos e manjericao. Simples, fresca e elegante.', 'Pao italiano, tomate, manjericao, alho, azeite, sal, pimenta', 'Torre fatias de pao. Esfregue alho. Cubra com tomates picados temperados com azeite, sal e manjericao. Sirva imediatamente.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbruschetta', FALSE, 4, 15, 'FACIL', 2),

('Bolinho de Bacalhau', 'Salgado portugues tradicional, crocante e saboroso. Perfeito como aperitivo ou lanche.', 'Bacalhau dessalgado, batata, ovos, cebola, salsinha, oleo para fritar', 'Cozinhe batatas e bacalhau. Amasse juntos. Adicione cebola, salsinha e ovos. Modele bolinhos e frite ate dourar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbolinhobacalhau', TRUE, 5, 50, 'MEDIO', 2),

('Croissant de Presunto e Queijo', 'Croissant folhado recheado com presunto e queijo. Cafe da manha especial.', 'Massa folhada, presunto, queijo, gema para pincelar', 'Abra a massa folhada. Corte em triangulos. Recheie com presunto e queijo. Enrole e pincele com gema. Asse ate dourar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcroissant', TRUE, 4, 30, 'FACIL', 2),

('Frango Grelhado com Legumes', 'Refeicao leve e proteica ideal para dietas. Saudavel sem perder o sabor.', 'Peito de frango, abobrinha, berinjela, pimentao, azeite, ervas', 'Tempere o frango com ervas. Grelhe ate dourar. Corte legumes e grelhe com azeite. Sirva juntos.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfrangogrelhado', TRUE, 4, 30, 'FACIL', 3),

('Omelete de Claras', 'Opcao proteica com baixo teor de gordura. Ideal para cafe da manha fitness.', 'Claras de ovo, espinafre, tomate, queijo cottage, temperos', 'Bata claras levemente. Despeje em frigideira antiaderente. Adicione recheios de um lado e dobre. Sirva quente.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQomeleteclaras', FALSE, 4, 10, 'FACIL', 3),

('Salmao ao Forno', 'Peixe assado rico em omega 3. Saudavel e sofisticado.', 'File de salmao, limao, alcaparras, azeite, dill, sal, pimenta', 'Tempere salmao com limao e temperos. Regue com azeite. Asse por 20 minutos a 200 graus. Finalize com alcaparras.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsalmaoforno', TRUE, 5, 30, 'FACIL', 3),

('Arroz Integral com Legumes', 'Acompanhamento nutritivo e rico em fibras. Base saudavel para qualquer refeicao.', 'Arroz integral, cenoura, vagem, milho, azeite, temperos', 'Cozinhe arroz integral. Refogue legumes picados em azeite. Misture com arroz e tempere. Sirva quente.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQarrozintegral', FALSE, 3, 45, 'FACIL', 3),

('Peixe ao Vapor com Gengibre', 'Prato asiatico leve e aromatico. Preserva todos os nutrientes do peixe.', 'File de peixe branco, gengibre, cebolinha, shoyu light, oleo de gergelim', 'Coloque peixe em prato refratario. Cubra com gengibre fatiado. Cozinhe no vapor por 15 minutos. Finalize com cebolinha e shoyu.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpeixevapor', FALSE, 4, 25, 'FACIL', 3),
('Carne Assada Magra', 'Carne de panela preparada sem gordura adicional. Sabor caseiro e saudavel.', 'Lagarto ou patinho, cebola, alho, tomate, louro, agua', 'Sele a carne em panela antiaderente. Adicione temperos e agua. Cozinhe em fogo baixo por 2 horas ate amaciar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcarneassada', TRUE, 4, 120, 'MEDIO', 3),

('Couve-Flor Gratinada Light', 'Legume gratinado com queijo light. Acompanhamento cremoso e saudavel.', 'Couve-flor, queijo cottage, leite desnatado, noz-moscada, sal', 'Cozinhe couve-flor no vapor. Prepare molho branco light. Cubra a couve-flor e gratine no forno ate dourar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcouveflorlight', FALSE, 4, 35, 'FACIL', 3),

('Lasanha de Berinjela', 'Lasanha sem massa tradicional, usando berinjela. Leve e muito saborosa.', 'Berinjelas, molho de tomate, ricota, mucarela, manjericao', 'Corte berinjelas em fatias e grelhe. Monte camadas alternando berinjela, molho, ricota e mucarela. Asse por 30 minutos.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlasanhaberinjela', TRUE, 4, 50, 'MEDIO', 4),

('Hamburguer de Grao de Bico', 'Hamburguer vegetariano proteico e saboroso. Alternativa saudavel a carne.', 'Grao de bico cozido, cebola, alho, cominho, salsinha, farinha de aveia', 'Processe grao de bico com temperos. Adicione farinha para dar liga. Modele hamburguers e grelhe ou asse. Sirva no pao com salada.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhamburguergraodebico', TRUE, 4, 30, 'FACIL', 4),

('Curry de Legumes', 'Prato indiano aromatico e reconfortante. Sabores exoticos em cada garfada.', 'Batata, cenoura, ervilha, leite de coco, curry, gengibre, alho', 'Refogue alho e gengibre. Adicione legumes e curry. Cubra com leite de coco e cozinhe ate os legumes ficarem macios.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcurrylegumes', FALSE, 4, 40, 'FACIL', 4),

('Risoto de Cogumelos', 'Risoto cremoso italiano com cogumelos variados. Elegante e cheio de umami.', 'Arroz arboreo, cogumelos variados, cebola, vinho branco, caldo de legumes, parmesao', 'Refogue cogumelos e reserve. Refogue cebola, adicione arroz e vinho. Adicione caldo aos poucos. Finalize com cogumelos e queijo.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrisotocogumelos', TRUE, 5, 35, 'MEDIO', 4),

('Tofu Grelhado com Vegetais', 'Prato asiatico leve e proteico. Perfeito para uma alimentacao plant-based.', 'Tofu firme, shoyu, gengibre, gergelim, brocolis, cenoura', 'Marine tofu em shoyu e gengibre. Grelhe ate dourar. Salteie vegetais e sirva com tofu. Finalize com gergelim.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtofugrelhado', FALSE, 4, 25, 'FACIL', 4),

('Espaguete ao Pesto', 'Massa italiana com molho de manjericao fresco. Aromatico e vibrante.', 'Espaguete, manjericao, pinhao, alho, azeite, parmesao', 'Bata manjericao, pinhao, alho e azeite ate formar pasta. Cozinhe a massa al dente. Misture com pesto e parmesao.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQespaguetepesto', TRUE, 5, 20, 'FACIL', 4),

('Bolinho de Espinafre', 'Salgado vegetariano nutritivo e saboroso. Rico em ferro e vitaminas.', 'Espinafre, ricota, ovos, farinha de trigo, cebola, temperos', 'Refogue espinafre. Misture com ricota, ovos e farinha. Tempere e modele bolinhos. Frite ou asse ate dourar.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbolinhoespinafre', FALSE, 4, 35, 'FACIL', 4),

('Tortilha Espanhola', 'Omelete espanhola grossa com batatas. Classica e versatil, serve quente ou fria.', 'Batatas, ovos, cebola, azeite, sal', 'Frite batatas e cebola em azeite ate dourar. Bata ovos e misture com batatas. Cozinhe em fogo baixo virando para dourar ambos os lados.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtortilhaespanhola', TRUE, 4, 40, 'MEDIO', 4),

('Chocolate Quente Cremoso', 'Bebida reconfortante para dias frios. Cremoso e irresistivel.', 'Leite, chocolate em po, acucar, creme de leite, canela', 'Aqueca leite com chocolate e acucar. Adicione creme de leite e bata ate ficar cremoso. Sirva quente com canela.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQchocolatequente', TRUE, 5, 15, 'FACIL', 5),

('Limonada Suica', 'Limonada cremosa e refrescante. Sucesso garantido em dias quentes.', 'Limoes, agua, acucar, leite condensado, gelo', 'Bata limoes inteiros com agua e acucar rapidamente. Coe. Adicione leite condensado e bata com gelo. Sirva gelado.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlimonadasuica', TRUE, 5, 10, 'FACIL', 5),

('Cha Mate Gelado', 'Bebida brasileira tradicional, refrescante e energizante. Perfeita para o verao.', 'Cha mate, limao, acucar, gelo', 'Prepare cha mate forte. Adoce enquanto quente. Deixe esfriar e adicione suco de limao. Sirva com muito gelo.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQchamategelado', FALSE, 4, 15, 'FACIL', 5),

('Quentao', 'Bebida tipica de festas juninas. Aquece corpo e alma.', 'Cachaca, gengibre, cravo, canela, acucar, agua', 'Faca calda com agua, acucar e especiarias. Adicione cachaca e aqueca sem ferver. Sirva quente.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQquentao', TRUE, 4, 20, 'FACIL', 5),

('Suco de Maracuja', 'Suco tropical refrescante e calmante. Rico em vitaminas e muito saboroso.', 'Polpa de maracuja, agua, acucar, gelo', 'Bata polpa de maracuja com agua e acucar. Coe para remover sementes. Sirva com gelo.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsucomaracuja', FALSE, 4, 10, 'FACIL', 5),

('Batida de Coco', 'Drink brasileiro doce e cremoso. Tropical e irresistivel.', 'Cachaca, leite de coco, leite condensado, gelo', 'Bata todos os ingredientes no liquidificador ate ficar cremoso. Sirva em copos gelados.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbatidacoco', TRUE, 5, 5, 'FACIL', 5),

('Cha de Camomila com Mel', 'Bebida calmante e reconfortante. Perfeita antes de dormir.', 'Camomila, mel, agua quente, limao', 'Prepare cha de camomila. Adoce com mel e adicione gotas de limao. Sirva quente.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQchacamomila', FALSE, 4, 10, 'FACIL', 5),

('Agua de Coco Natural', 'Bebida isotonica natural e refrescante. Hidratacao pura e saborosa.', 'Coco verde', 'Abra o coco verde com facão. Despeje a agua em copo com gelo. Sirva imediatamente.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaguadecoco', TRUE, 5, 5, 'FACIL', 5),

('Lassi de Manga', 'Bebida indiana cremosa com iogurte e manga. Refrescante e exotica.', 'Iogurte natural, manga madura, acucar, cardamomo, gelo', 'Bata manga, iogurte, acucar e cardamomo ate ficar cremoso. Sirva gelado.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlassimanga', FALSE, 4, 10, 'FACIL', 5);
